/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package it.iccu.sbn.ejb.vo.servizi.erogazione;

import it.iccu.sbn.ejb.vo.SerializableVO;

import java.util.Date;

/**
 * TblPenalitaServizio generated by MyEclipse Persistence Tools
 */

public class PenalitaServizioVO extends SerializableVO {

	private static final long serialVersionUID = 8668120334737050209L;
	private String codBib;
	private String codTipoServ;
	private String codServ;
	private Date tsIns;
	private Date tsVar;
	private Short ggSosp = 0;
	private Long coeffSosp = new Long(0);
	private Short ggTolleranza = 0;
	private String flCanc;
	private String uteIns;
	private String uteVar;

	// Constructors

	/** default constructor */
	public PenalitaServizioVO() {
	}

	/** full constructor */
	public PenalitaServizioVO(String codBib, String codTipoServ,
			String codServ, Date tsIns, Date tsVar, Short ggSosp,
			Long coeffSosp, String flCanc, String uteIns, String uteVar) {

		this.codBib = codBib;
		this.codTipoServ = codTipoServ;
		this.codServ = codServ;
		this.tsIns = tsIns;
		this.tsVar = tsVar;
		this.ggSosp = ggSosp;
		this.coeffSosp = coeffSosp;
		this.flCanc = flCanc;
		this.uteIns = uteIns;
		this.uteVar = uteVar;
	}

	// Property accessors

	public Date getTsIns() {
		return this.tsIns;
	}

	public void setTsIns(Date tsIns) {
		this.tsIns = tsIns;
	}

	public Date getTsVar() {
		return this.tsVar;
	}

	public void setTsVar(Date tsVar) {
		this.tsVar = tsVar;
	}

	public Short getGgTolleranza() {
		return ggTolleranza;
	}

	public void setGgTolleranza(Short ggTolleranza) {
		this.ggTolleranza = ggTolleranza;
	}

	public Short getGgSosp() {
		return this.ggSosp;
	}

	public void setGgSosp(Short ggSosp) {
		//this.ggSosp = ( ggSosp==null || ggSosp.shortValue()==0 ? null : ggSosp);
		this.ggSosp = ggSosp;
	}

	public Long getCoeffSosp() {
		return this.coeffSosp;
	}

	public void setCoeffSosp(Long coeffSosp) {
		//this.coeffSosp = (coeffSosp==null || coeffSosp.longValue()==0 ? null : coeffSosp);
		this.coeffSosp = coeffSosp;
	}

	public String getFlCanc() {
		return this.flCanc;
	}

	public void setFlCanc(String flCanc) {
		this.flCanc = flCanc;
	}

	public String getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(String uteIns) {
		this.uteIns = uteIns;
	}

	public String getUteVar() {
		return this.uteVar;
	}

	public void setUteVar(String uteVar) {
		this.uteVar = uteVar;
	}

	public String getCodBib() {
		return codBib;
	}

	public void setCodBib(String codBib) {
		this.codBib = codBib;
	}

	public String getCodServ() {
		return codServ;
	}

	public void setCodServ(String codServ) {
		this.codServ = codServ;
	}

	public String getCodTipoServ() {
		return codTipoServ;
	}

	public void setCodTipoServ(String codTipoServ) {
		this.codTipoServ = codTipoServ;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (this.getClass() != obj.getClass())
			return false;
		PenalitaServizioVO other = (PenalitaServizioVO) obj;

		if (codBib==null) {
			if (other.codBib!=null) return false;
		} else {
			if (!codBib.equals(other.codBib)) return false;
		}
		if (codTipoServ==null) {
			if (other.codTipoServ!=null) return false;
		} else {
			if (!codTipoServ.equals(other.codTipoServ)) return false;
		}
		if (codServ==null) {
			if (other.codServ!=null) return false;
		} else {
			if (!codServ.equals(other.codServ)) return false;
		}
		if (ggSosp==null) {
			if (other.ggSosp!=null) return false;
		} else {
			if (!ggSosp.equals(other.ggSosp)) return false;
		}
		if (coeffSosp==null) {
			if (other.coeffSosp!=null) return false;
		} else {
			if (!coeffSosp.equals(other.coeffSosp)) return false;
		}

		return true;
	}

}
