/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package it.iccu.sbn.ejb.vo.servizi.erogazione;

import it.iccu.sbn.ejb.vo.BaseVO;

/**
 * TblServizi generated by MyEclipse Persistence Tools
 */

public class ServizioBibliotecaVO extends BaseVO {

	private static final long serialVersionUID = -2995627456649187811L;
	private int idServizio;
	private String codPolo;
	private String codBib;
	private String codTipoServ;
	private String descrTipoServ;
	private String codServ;
	private String descr;
	private Short numMaxRich;
	private Short numMaxMov;
	private Short durMov;
	private Short durMaxRinn1;
	private Short durMaxRinn2;
	private Short durMaxRinn3;
	private Short numMaxRiprod;
	private Short numMaxPrenPosto;
	private Short numGgPrepSupp;
	private String orarioLimitePrepSupp;
	private Short maxGgAnt;
	private Short maxGgDep;
	private Short maxGgCons;
	private Long NMaxPren;
	private Long NMaxGgvalPren;

	private Short giorniRestituzioneRichiedente;

	// Dati penalità
	private PenalitaServizioVO penalita = new PenalitaServizioVO();

	private String codServizioILL;

	// Constructors

	/** default constructor */
	public ServizioBibliotecaVO() {
	}

	// Property accessors

	public String getDescrTipoServ() {
		return descrTipoServ;
	}

	public void setDescrTipoServ(String descrTipoServ) {
		this.descrTipoServ = trimAndSet(descrTipoServ);
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public Short getNumMaxRich() {
		return this.numMaxRich;
	}

	public void setNumMaxRich(Short numMaxRich) {
		this.numMaxRich = numMaxRich;
	}

	public Short getNumMaxMov() {
		return this.numMaxMov;
	}

	public void setNumMaxMov(Short numMaxMov) {
		this.numMaxMov = numMaxMov;
	}

	public Short getDurMov() {
		return this.durMov;
	}

	public void setDurMov(Short durMov) {
		this.durMov = durMov;
	}

	public Short getDurMaxRinn1() {
		return this.durMaxRinn1;
	}

	public void setDurMaxRinn1(Short durMaxRinn1) {
		this.durMaxRinn1 = durMaxRinn1;
	}

	public Short getDurMaxRinn2() {
		return this.durMaxRinn2;
	}

	public void setDurMaxRinn2(Short durMaxRinn2) {
		this.durMaxRinn2 = durMaxRinn2;
	}

	public Short getDurMaxRinn3() {
		return this.durMaxRinn3;
	}

	public void setDurMaxRinn3(Short durMaxRinn3) {
		this.durMaxRinn3 = durMaxRinn3;
	}

	public Short getNumMaxRiprod() {
		return this.numMaxRiprod;
	}

	public void setNumMaxRiprod(Short numMaxRiprod) {
		this.numMaxRiprod = numMaxRiprod;
	}

	public Short getNumMaxPrenPosto() {
		return numMaxPrenPosto;
	}

	public void setNumMaxPrenPosto(Short numMaxPrenPosto) {
		this.numMaxPrenPosto = numMaxPrenPosto;
	}

	public Short getNumGgPrepSupp() {
		return numGgPrepSupp;
	}

	public void setNumGgPrepSupp(Short numGgPrepSupp) {
		this.numGgPrepSupp = numGgPrepSupp;
	}

	public String getOrarioLimitePrepSupp() {
		return orarioLimitePrepSupp;
	}

	public void setOrarioLimitePrepSupp(String orarioLimitePrepSupp) {
		this.orarioLimitePrepSupp = trimAndSet(orarioLimitePrepSupp);
	}

	public Short getMaxGgAnt() {
		return this.maxGgAnt;
	}

	public void setMaxGgAnt(Short maxGgAnt) {
		this.maxGgAnt = maxGgAnt;
	}

	public Short getMaxGgDep() {
		return this.maxGgDep;
	}

	public void setMaxGgDep(Short maxGgDep) {
		this.maxGgDep = maxGgDep;
	}

	public Short getMaxGgCons() {
		return this.maxGgCons;
	}

	public void setMaxGgCons(Short maxGgCons) {
		this.maxGgCons = maxGgCons;
	}

	public Long getNMaxPren() {
		return this.NMaxPren;
	}

	public void setNMaxPren(Long NMaxPren) {
		this.NMaxPren = NMaxPren;
	}

	public Long getNMaxGgvalPren() {
		return this.NMaxGgvalPren;
	}

	public void setNMaxGgvalPren(Long NMaxGgvalPren) {
		this.NMaxGgvalPren = NMaxGgvalPren;
	}

	public Short getGiorniRestituzioneRichiedente() {
		return giorniRestituzioneRichiedente;
	}

	public void setGiorniRestituzioneRichiedente(Short giorniRestituzioneRichiedente) {
		this.giorniRestituzioneRichiedente = giorniRestituzioneRichiedente;
	}

	public String getUteIns() {
		return this.uteIns;
	}

	public void setUteIns(String uteIns) {
		this.uteIns = uteIns;
	}

	public String getFlCanc() {
		return this.flCanc;
	}

	public void setFlCanc(String flCanc) {
		this.flCanc = flCanc;
	}

	public String getCodBib() {
		return codBib;
	}

	public void setCodBib(String codBib) {
		this.codBib = toUpperCase(codBib);
	}

	public String getCodServ() {
		return codServ;
	}

	public void setCodServ(String codServ) {
		this.codServ = toUpperCase(codServ);
	}

	public String getCodTipoServ() {
		return codTipoServ;
	}

	public void setCodTipoServ(String codTipoServ) {
		this.codTipoServ = toUpperCase(codTipoServ);
	}

	public PenalitaServizioVO getPenalita() {
		return penalita;
	}

	public void setPenalita(PenalitaServizioVO penalita) {
		this.penalita = penalita;
	}

	public int getIdServizio() {
		return idServizio;
	}

	public void setIdServizio(int idServizio) {
		this.idServizio = idServizio;
	}

	public String getCodPolo() {
		return codPolo;
	}

	public void setCodPolo(String codPolo) {
		this.codPolo = toUpperCase(codPolo);
	}

	public boolean impostataPenalita() {
		if (getPenalita() != null) {
			if (getPenalita().getGgSosp() != null && getPenalita().getGgSosp().longValue() > 0) {
				return true;
			}
			if (getPenalita().getCoeffSosp() != null && getPenalita().getCoeffSosp().longValue() > 0) {
				return true;
			}
			return false;
		}
		return false;
	}

	public String getCodServizioILL() {
		return codServizioILL;
	}

	public void setCodServizioILL(String codServizioILL) {
		this.codServizioILL = trimAndSet(codServizioILL);
	}

	public boolean isILL() {
		return isFilled(codServizioILL);
	}

	@Override
	public boolean isNuovo() {
		return idServizio == 0;
	}

	public String toString() {
		return codPolo + codBib + " " + codTipoServ + " " + codServ;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((NMaxGgvalPren == null) ? 0 : NMaxGgvalPren.hashCode());
		result = prime * result
				+ ((NMaxPren == null) ? 0 : NMaxPren.hashCode());
		result = prime * result + ((codBib == null) ? 0 : codBib.hashCode());
		result = prime * result + ((codPolo == null) ? 0 : codPolo.hashCode());
		result = prime * result + ((codServ == null) ? 0 : codServ.hashCode());
		result = prime * result
				+ ((codTipoServ == null) ? 0 : codTipoServ.hashCode());
		result = prime * result + ((descr == null) ? 0 : descr.hashCode());
		result = prime * result
				+ ((descrTipoServ == null) ? 0 : descrTipoServ.hashCode());
		result = prime * result
				+ ((durMaxRinn1 == null) ? 0 : durMaxRinn1.hashCode());
		result = prime * result
				+ ((durMaxRinn2 == null) ? 0 : durMaxRinn2.hashCode());
		result = prime * result
				+ ((durMaxRinn3 == null) ? 0 : durMaxRinn3.hashCode());
		result = prime * result + ((durMov == null) ? 0 : durMov.hashCode());
		result = prime * result + ((flCanc == null) ? 0 : flCanc.hashCode());
		result = prime * result + idServizio;
		result = prime * result
				+ ((maxGgAnt == null) ? 0 : maxGgAnt.hashCode());
		result = prime * result
				+ ((maxGgCons == null) ? 0 : maxGgCons.hashCode());
		result = prime * result
				+ ((maxGgDep == null) ? 0 : maxGgDep.hashCode());
		result = prime * result
				+ ((numMaxMov == null) ? 0 : numMaxMov.hashCode());
		result = prime * result
				+ ((numMaxRich == null) ? 0 : numMaxRich.hashCode());
		result = prime * result
				+ ((numMaxRiprod == null) ? 0 : numMaxRiprod.hashCode());
		result = prime * result
				+ ((penalita == null) ? 0 : penalita.hashCode());
		result = prime * result + ((tsIns == null) ? 0 : tsIns.hashCode());
		result = prime * result + ((tsVar == null) ? 0 : tsVar.hashCode());
		result = prime * result + ((uteIns == null) ? 0 : uteIns.hashCode());
		result = prime * result + ((uteVar == null) ? 0 : uteVar.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ServizioBibliotecaVO other = (ServizioBibliotecaVO) obj;
		if (NMaxGgvalPren == null) {
			if (other.NMaxGgvalPren != null)
				return false;
		} else if (!NMaxGgvalPren.equals(other.NMaxGgvalPren))
			return false;
		if (NMaxPren == null) {
			if (other.NMaxPren != null)
				return false;
		} else if (!NMaxPren.equals(other.NMaxPren))
			return false;
		if (codBib == null) {
			if (other.codBib != null)
				return false;
		} else if (!codBib.equals(other.codBib))
			return false;
		if (codPolo == null) {
			if (other.codPolo != null)
				return false;
		} else if (!codPolo.equals(other.codPolo))
			return false;
		if (codServ == null) {
			if (other.codServ != null)
				return false;
		} else if (!codServ.equals(other.codServ))
			return false;
		if (codTipoServ == null) {
			if (other.codTipoServ != null)
				return false;
		} else if (!codTipoServ.equals(other.codTipoServ))
			return false;
		if (descr == null) {
			if (other.descr != null)
				return false;
		} else if (!descr.equals(other.descr))
			return false;
		if (descrTipoServ == null) {
			if (other.descrTipoServ != null)
				return false;
		} else if (!descrTipoServ.equals(other.descrTipoServ))
			return false;
		if (durMaxRinn1 == null) {
			if (other.durMaxRinn1 != null)
				return false;
		} else if (!durMaxRinn1.equals(other.durMaxRinn1))
			return false;
		if (durMaxRinn2 == null) {
			if (other.durMaxRinn2 != null)
				return false;
		} else if (!durMaxRinn2.equals(other.durMaxRinn2))
			return false;
		if (durMaxRinn3 == null) {
			if (other.durMaxRinn3 != null)
				return false;
		} else if (!durMaxRinn3.equals(other.durMaxRinn3))
			return false;
		if (durMov == null) {
			if (other.durMov != null)
				return false;
		} else if (!durMov.equals(other.durMov))
			return false;
		if (flCanc == null) {
			if (other.flCanc != null)
				return false;
		} else if (!flCanc.equals(other.flCanc))
			return false;
		if (idServizio != other.idServizio)
			return false;
		if (maxGgAnt == null) {
			if (other.maxGgAnt != null)
				return false;
		} else if (!maxGgAnt.equals(other.maxGgAnt))
			return false;
		if (maxGgCons == null) {
			if (other.maxGgCons != null)
				return false;
		} else if (!maxGgCons.equals(other.maxGgCons))
			return false;
		if (maxGgDep == null) {
			if (other.maxGgDep != null)
				return false;
		} else if (!maxGgDep.equals(other.maxGgDep))
			return false;
		if (numMaxMov == null) {
			if (other.numMaxMov != null)
				return false;
		} else if (!numMaxMov.equals(other.numMaxMov))
			return false;
		if (numMaxRich == null) {
			if (other.numMaxRich != null)
				return false;
		} else if (!numMaxRich.equals(other.numMaxRich))
			return false;
		if (numMaxRiprod == null) {
			if (other.numMaxRiprod != null)
				return false;
		} else if (!numMaxRiprod.equals(other.numMaxRiprod))
			return false;
		if (numMaxPrenPosto == null) {
			if (other.numMaxPrenPosto != null)
				return false;
		} else if (!numMaxPrenPosto.equals(other.numMaxPrenPosto))
			return false;
		if (numGgPrepSupp == null) {
			if (other.numGgPrepSupp != null)
				return false;
		} else if (!numGgPrepSupp.equals(other.numGgPrepSupp))
			return false;
		if (orarioLimitePrepSupp == null) {
			if (other.orarioLimitePrepSupp != null)
				return false;
		} else if (!orarioLimitePrepSupp.equals(other.orarioLimitePrepSupp))
			return false;
		if (penalita == null) {
			if (other.penalita != null)
				return false;
		} else if (!penalita.equals(other.penalita))
			return false;
		if (tsIns == null) {
			if (other.tsIns != null)
				return false;
		} else if (!tsIns.equals(other.tsIns))
			return false;
		if (tsVar == null) {
			if (other.tsVar != null)
				return false;
		} else if (!tsVar.equals(other.tsVar))
			return false;
		if (uteIns == null) {
			if (other.uteIns != null)
				return false;
		} else if (!uteIns.equals(other.uteIns))
			return false;
		if (uteVar == null) {
			if (other.uteVar != null)
				return false;
		} else if (!uteVar.equals(other.uteVar))
			return false;
		if (giorniRestituzioneRichiedente == null) {
			if (other.giorniRestituzioneRichiedente != null)
				return false;
		} else if (!giorniRestituzioneRichiedente.equals(other.giorniRestituzioneRichiedente))
			return false;
		return true;
	}

	@Override
	public int getRepeatableId() {
		return (codTipoServ + '-' + codServ).hashCode();
	}

}
