/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.services.bibliografica;

import it.iccu.sbn.ejb.dao.DAOException;
import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.exception.DataException;
import it.iccu.sbn.ejb.exception.ValidationException;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.AllineaVO;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.ElaborazioniDifferiteOutputVo;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.ImportaLegamiBidAltroIdVO;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.LocalizzazioneMassivaVO;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.ParametriRichiestaElaborazioneDifferitaVO;
import it.iccu.sbn.ejb.vo.gestionestampe.common.StampaType;
import it.iccu.sbn.ejb.vo.gestionestampe.common.StampeOnlineVO;
import it.iccu.sbn.servizi.batch.BatchLogWriter;

import java.rmi.RemoteException;

/**
 * Remote interface for ServiziBibliografici.
 * @generated
 * @wtp generated
 */
public interface ServiziBibliografici
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DAOException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public it.iccu.sbn.vo.custom.bibliografica.AreaDatiServizioInterrTitoloCusVO servizioDatiTitoloPerBid( java.lang.String bid,java.lang.String ticket )
      throws it.iccu.sbn.ejb.dao.DAOException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws RemoteException
    * @throws ApplicationException
    * @throws DataException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public StampeOnlineVO stampeOnline( String ticket, StampaType tipoStampa, java.util.List parametri )
      throws ApplicationException, DataException, ValidationException, RemoteException;

	public ElaborazioniDifferiteOutputVo localizzazioneMassiva(
			LocalizzazioneMassivaVO richiesta, BatchLogWriter blw)
			throws ApplicationException, ValidationException, RemoteException;

	public ElaborazioniDifferiteOutputVo allineamenti(
			ParametriRichiestaElaborazioneDifferitaVO richiesta, BatchLogWriter blw)
			throws ApplicationException, ValidationException, RemoteException;

	public ElaborazioniDifferiteOutputVo importaLegamiBidOcn(ImportaLegamiBidAltroIdVO richiesta, BatchLogWriter blw)
			throws ApplicationException, ValidationException, RemoteException;

	public AllineaVO scaricaFileAllineamentoBaseLocale(AllineaVO areaDatiPass,
			java.lang.String ticket) throws it.iccu.sbn.ejb.dao.DAOException, java.rmi.RemoteException;

	public void spostaAltroIdPerFusione(String idElementoEliminato, String idElementoAccorpante, String uteVar) throws it.iccu.sbn.ejb.dao.DAOException, java.rmi.RemoteException;
}
