/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.services.servizi;

/**
 * Session layer for ServiziErogazioneServizi.
 * @generated
 * @wtp generated
 */
public class ServiziErogazioneServiziSession
   extends it.iccu.sbn.ejb.services.servizi.ServiziErogazioneServiziBean
   implements javax.ejb.SessionBean
{
	private static final long serialVersionUID = -416140631128509268L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbRemove()
   {
   }

}
