/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.services.servizi;

/**
 * Home interface for ServiziErogazioneServizi.
 * @generated
 * @wtp generated
 */
public interface ServiziErogazioneServiziHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServiziErogazioneServizi";
   public static final String JNDI_NAME="sbnWeb/ServiziErogazioneServizi";

   public it.iccu.sbn.ejb.services.servizi.ServiziErogazioneServizi create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
