/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

import it.iccu.sbn.ejb.vo.OutputStampaVo;
import it.iccu.sbn.ejb.vo.stampe.StampaOnLineVO;

import java.rmi.RemoteException;

/**
 * Remote interface for RegistriIngresso.
 * @generated
 * @wtp generated
 */
public interface SBNStampeStrumentiPatrimonio
   extends javax.ejb.EJBObject, SbnStampeBaseRemote {

	OutputStampaVo stampaModuloPrelievo(StampaOnLineVO stampaVO) throws RemoteException;
}