/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Home interface for Fattura.
 * @generated
 * @wtp generated
 */
public interface SBNStampeFatturaHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeFatturaOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeFatturaOnLine";

   public SBNStampeFattura create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
