/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.ElaborazioniDifferiteOutputVo;
import it.iccu.sbn.ejb.vo.servizi.batch.ParametriBatchSollecitiVO;
import it.iccu.sbn.servizi.batch.BatchLogWriter;

import java.rmi.RemoteException;

public interface SBNStampeUtenti extends javax.ejb.EJBObject,
		SbnStampeBaseRemote {

	ElaborazioniDifferiteOutputVo elaboraSolleciti(
			ParametriBatchSollecitiVO stampaVO, BatchLogWriter blog) throws ApplicationException, RemoteException;
}