/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Home interface for SuggerimentiBibliotecario.
 * @generated
 * @wtp generated
 */
public interface SBNStampeSuggerimentiBibliotecarioHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeSuggerimentiBibliotecarioOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeSuggerimentiBibliotecarioOnLine";

   public SBNStampeSuggerimentiBibliotecario create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
