/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

import java.rmi.RemoteException;

import javax.ejb.EJBException;
import javax.ejb.SessionBean;
import javax.ejb.SessionContext;

public class SBNStampeSemanticaSession extends SBNStampeSemanticaBean implements SessionBean {

	private static final long serialVersionUID = 6162001884747661224L;

	public void ejbActivate() {

	}

	public void ejbPassivate() {
	}

	public void setSessionContext(SessionContext ctx) throws EJBException, RemoteException {
		super.setSessionContext(ctx);
	}

	public void unsetSessionContext() {
	}

	public void ejbCreate() {
	}

	public void ejbRemove() {
	}

}
