/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Session layer for Richiesta.
 * @generated
 * @wtp generated
 */
public class SBNStampeRichiestaSession
   extends it.iccu.sbn.ejb.domain.stampe.SBNStampeRichiestaBean
   implements javax.ejb.SessionBean
{
   /**
	 * 
	 */
	private static final long serialVersionUID = -4788853117806645456L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbCreate() {
	}

   public void ejbRemove()
   {
   }

}
