/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Session layer for Comunicazione.
 * @generated
 * @wtp generated
 */
public class SBNStampeComunicazioneSession
   extends it.iccu.sbn.ejb.domain.stampe.SBNStampeComunicazioneBean
   implements javax.ejb.SessionBean
{
   /**
	 * 
	 */
	private static final long serialVersionUID = -6804850815070921719L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbCreate() {
	}

   public void ejbRemove()
   {
   }

}
