/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Home interface for Collocazione.
 * @generated
 * @wtp generated
 */
public interface SBNStampeFornitoriHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeFornitoriOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeFornitoriOnLine";

   public SBNStampeFornitori create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
