/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Home interface for Collocazione.
 * @generated
 * @wtp generated
 */
public interface SBNStampeUtentiHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeUtentiOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeUtentiOnLine";

   public SBNStampeUtenti create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
