/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Home interface for Bollettario.
 * @generated
 * @wtp generated
 */
public interface SBNStampeBollettarioHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeBollettarioOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeBollettarioOnLine";

   public SBNStampeBollettario create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
