/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Home interface for BuoniOrdine.
 * @generated
 * @wtp generated
 */
public interface SBNStampeBuoniOrdineHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeBuoniOrdineOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeBuoniOrdineOnLine";

   public SBNStampeBuoniOrdine create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
