/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;



/**
 * Remote interface for RegistriIngresso.
 * @generated
 * @wtp generated
 */
public interface SBNStampeRegistroTopografico
   extends javax.ejb.EJBObject, SbnStampeBaseRemote {}