/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Home interface for TermniThesauro.
 * @generated
 * @wtp generated
 */
public interface SBNStampeTerminiThesauroHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeTerminiThesauroOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeTerminiThesauroOnLine";

   public SBNStampeTerminiThesauro create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
