/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.stampe;

/**
 * Home interface for Spese.
 * @generated
 * @wtp generated
 */
public interface SBNStampeListaFascicoliHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeListaFascicoliOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeListaFascicoliOnLine";

   public SBNStampeListaFascicoli create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
