/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.servizi.serviziweb;

/**
 * Home interface for ServiziWeb.
 * @generated
 * @wtp generated
 */
public interface ServiziWebHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ServiziWeb";
   public static final String JNDI_NAME="sbnWeb/ServiziWeb";

   public it.iccu.sbn.ejb.domain.servizi.serviziweb.ServiziWeb create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
