/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.servizi.serviziweb;

/**
 * Session layer for ServiziWeb.
 *
 * @generated
 * @wtp generated
 */
public class ServiziWebSession extends ServiziWebBean implements
		javax.ejb.SessionBean {

	private static final long serialVersionUID = 6796315909715615650L;

	public void ejbActivate() {
	}

	public void ejbPassivate() {
	}

	public void setSessionContext(javax.ejb.SessionContext ctx)
			throws javax.ejb.EJBException, java.rmi.RemoteException {
		super.setSessionContext(ctx);
	}

	public void unsetSessionContext() {
	}

	public void ejbRemove() {
	}

}
