/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.statistiche;

/**
 * Home interface for RegistriIngresso.
 * @generated
 * @wtp generated
 */
public interface SBNStatisticheHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStatisticheOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStatisticheOnLine";

   public SBNStatistiche create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
