/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.statistiche;

import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.exception.DataException;
import it.iccu.sbn.ejb.exception.ResourceNotFoundException;
import it.iccu.sbn.ejb.exception.ValidationException;
import it.iccu.sbn.ejb.vo.documentofisico.CodiceVO;
import it.iccu.sbn.ejb.vo.statistiche.AreaVO;
import it.iccu.sbn.ejb.vo.statistiche.DettVarStatisticaVO;
import it.iccu.sbn.ejb.vo.statistiche.StatisticaVO;
import it.iccu.sbn.servizi.batch.BatchLogWriter;

import java.rmi.RemoteException;
import java.util.List;
import java.util.Map;

/**
 * Remote interface for AmministrazioneBiblioteca.
 *
 * @generated
 * @wtp generated
 */
public interface StatisticheSBN extends javax.ejb.EJBObject {

	public List<AreaVO> getAreeUtente(Map attivita) throws RemoteException;
	public List<StatisticaVO> getListaStatistiche(String area, String ticket) throws RemoteException;
	public List<DettVarStatisticaVO> getDettVarStatistica(int idStatistica, String ticket) throws RemoteException;
	public boolean elaboraStatistica(StatisticaVO statistica, String ticket, BatchLogWriter batchLog)
			throws ResourceNotFoundException, ApplicationException, ValidationException, DataException, RemoteException;
	public List<CodiceVO> getListaCodDescrDaTabGenerica(String codPolo, String valori0/*codBib*/, String valori1/*tabella*/,
			String  valori2/*codice*/,  String valori3/*descrizione*/, String valori4/*valore codBib*/, String ticket)
			throws ResourceNotFoundException, ApplicationException, ValidationException, DataException, RemoteException;
}