/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.statistiche;

/**
 * Session layer for StatisticheSBN.
 * @generated
 * @wtp generated
 */
public class StatisticheSBNSession
   extends it.iccu.sbn.ejb.domain.statistiche.StatisticheSBNBean
   implements javax.ejb.SessionBean
{
   /**
	 * 
	 */
	private static final long serialVersionUID = 4570988545960360339L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbRemove()
   {
   }

}
