/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.acquisizioni;

import it.iccu.sbn.command.CommandInvokeVO;
import it.iccu.sbn.command.CommandResultVO;
import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.exception.ResourceNotFoundException;
import it.iccu.sbn.ejb.exception.ValidationException;
import it.iccu.sbn.ejb.vo.acquisizioni.FornitoreVO;
import it.iccu.sbn.ejb.vo.acquisizioni.OrdiniVO;
import it.iccu.sbn.ejb.vo.gestionebibliografica.AreaDatiVariazioneReturnVO;
import it.iccu.sbn.periodici.vo.SchedaInventarioVO;
import it.iccu.sbn.periodici.vo.SchedaPeriodicoVO;
import it.iccu.sbn.persistence.dao.exception.DaoManagerException;
import it.iccu.sbn.web.exception.SbnBaseException;

import java.rmi.RemoteException;
import java.util.List;

import org.hibernate.exception.DataException;

/**
 * Remote interface for Acquisizioni.
 * @generated
 * @wtp generated
 */
public interface Acquisizioni
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaFatture( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppFatturaVO ricercaFatture )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaProfili( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppProfiloVO ricercaProfili )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaComunicazioni( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppComunicazioneVO ricercaComunicazioni )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciCambio( it.iccu.sbn.ejb.vo.acquisizioni.CambioVO cambio )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaCambio( it.iccu.sbn.ejb.vo.acquisizioni.CambioVO cambio )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaCambio( it.iccu.sbn.ejb.vo.acquisizioni.CambioVO cambio )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciProfilo( it.iccu.sbn.ejb.vo.acquisizioni.StrutturaProfiloVO profilo )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaProfilo( it.iccu.sbn.ejb.vo.acquisizioni.StrutturaProfiloVO profilo )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaProfilo( it.iccu.sbn.ejb.vo.acquisizioni.StrutturaProfiloVO profilo )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaCambi( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppCambioVO ricercaCambi )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppCambioVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppCambioVO prova )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaCambioVO( it.iccu.sbn.ejb.vo.acquisizioni.CambioVO prova )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicerca( java.util.List listaCambi )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getListaOrdini(  )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaOrdini( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppOrdiniVO ricercaOrdini )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciOrdine( it.iccu.sbn.ejb.vo.acquisizioni.OrdiniVO ordine )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciOrdineBiblHib(OrdiniVO ordine, List listaBiblAff)
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaOrdine( it.iccu.sbn.ejb.vo.acquisizioni.OrdiniVO ordine )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaOrdine( it.iccu.sbn.ejb.vo.acquisizioni.OrdiniVO ordine )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaBiblAffiliate( java.lang.String codiceBiblioteca, java.lang.String codiceAttivita )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaFornitori( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppFornitoreVO ricercaFornitori )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


	// Evolutiva Ba1 - Editori almaviva2 Novembre 2012
	// Inserito nuovo metodo per la ricerca dei titoli collegati in modo esplicito o implicito all'editore selezionato
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaTitCollEditori(
		   it.iccu.sbn.ejb.vo.acquisizioni.RicercaTitCollEditoriVO ricercaTitCollEditoriVO, String ticket )
      	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public java.util.List getRicercaEditCollTitolo(
		   it.iccu.sbn.ejb.vo.acquisizioni.RicercaTitCollEditoriVO ricercaTitCollEditoriVO, String ticket )
      	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


   public java.util.List getAreeIsbdListaBid( java.util.List listaBid)
  		throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public AreaDatiVariazioneReturnVO gestioneLegameTitEdit(
		   it.iccu.sbn.ejb.vo.gestionebibliografica.titolo.AreaDatiLegameTitoloVO areaDatiLegameTitoloVO, String ticket)
   		throws RemoteException, ValidationException;;




   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciFornitore( it.iccu.sbn.ejb.vo.acquisizioni.FornitoreVO fornitore )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaFornitore( it.iccu.sbn.ejb.vo.acquisizioni.FornitoreVO fornitore )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaBilanci( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppBilancioVO ricercaBilanci )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciFattura( it.iccu.sbn.ejb.vo.acquisizioni.FatturaVO fattura )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciComunicazione( it.iccu.sbn.ejb.vo.acquisizioni.ComunicazioneVO comunicazione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciBilancio( it.iccu.sbn.ejb.vo.acquisizioni.BilancioVO bilancio )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaBilancio( it.iccu.sbn.ejb.vo.acquisizioni.BilancioVO bilancio )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaFattura( it.iccu.sbn.ejb.vo.acquisizioni.FatturaVO fattura )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaComunicazione( it.iccu.sbn.ejb.vo.acquisizioni.ComunicazioneVO comunicazione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaSezioni( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppSezioneVO ricercaSezioni )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciSezione( it.iccu.sbn.ejb.vo.acquisizioni.SezioneVO sezione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaSezione( it.iccu.sbn.ejb.vo.acquisizioni.SezioneVO sezione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaSezione( it.iccu.sbn.ejb.vo.acquisizioni.SezioneVO sezione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaBuoniOrd( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppBuoniOrdineVO ricercaBuoniOrd )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciBuonoOrd( it.iccu.sbn.ejb.vo.acquisizioni.BuoniOrdineVO buonoOrd )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaBuonoOrd( it.iccu.sbn.ejb.vo.acquisizioni.BuoniOrdineVO buonoOrd )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaBuonoOrd( it.iccu.sbn.ejb.vo.acquisizioni.BuoniOrdineVO buonoOrd )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaFattura( it.iccu.sbn.ejb.vo.acquisizioni.FatturaVO fattura )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaBilancio(it.iccu.sbn.ejb.vo.acquisizioni.BilancioVO bilancio)
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaComunicazione( it.iccu.sbn.ejb.vo.acquisizioni.ComunicazioneVO comunicazione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaBuoniOrd( java.util.List listaBuoniOrd )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppBuoniOrdineVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppBuoniOrdineVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaBuoniOrdineVO( it.iccu.sbn.ejb.vo.acquisizioni.BuoniOrdineVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaSezioni( java.util.List listaSezioni )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppSezioneVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppSezioneVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaSezioneVO( it.iccu.sbn.ejb.vo.acquisizioni.SezioneVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaProfili( java.util.List listaProfili )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaComunicazioni( java.util.List listaComunicazioni )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaFatture( java.util.List listaFatture )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaBilanci( java.util.List listaBilanci )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppProfiloVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppProfiloVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppComunicazioneVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppComunicazioneVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppFatturaVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppFatturaVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppBilancioVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppBilancioVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaBilancioVO( it.iccu.sbn.ejb.vo.acquisizioni.BilancioVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaComunicazioneVO( it.iccu.sbn.ejb.vo.acquisizioni.ComunicazioneVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaStrutturaProfiloVO( it.iccu.sbn.ejb.vo.acquisizioni.StrutturaProfiloVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaFatturaVO( it.iccu.sbn.ejb.vo.acquisizioni.FatturaVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaFornitori( java.util.List listaFornitori )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppOrdiniVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppOrdiniVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaOrdini( java.util.List listaOrdini )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaOrdiniVO( it.iccu.sbn.ejb.vo.acquisizioni.OrdiniVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaFornitoreVO( it.iccu.sbn.ejb.vo.acquisizioni.FornitoreVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppFornitoreVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppFornitoreVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.lang.String struttura( java.lang.String sqlString )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean strIsAlfabetic( java.lang.String data )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean strIsNumeric( java.lang.String data )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean create stub    */
   public int validaDataPassata( java.lang.String data )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getTitolo( java.util.List listaBid,java.lang.String ticket )
      throws it.iccu.sbn.ejb.exception.ValidationException, org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws DaoManagerException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getTitoloOrdine( java.lang.String bidPassato )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws DaoManagerException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public it.iccu.sbn.ejb.vo.acquisizioni.TitoloACQVO getTitoloOrdineBis( java.lang.String bidPassato )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws DaoManagerException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public it.iccu.sbn.ejb.vo.acquisizioni.TitoloACQVO getTitoloRox( java.lang.String bidPassato )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.persistence.dao.exception.DaoManagerException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws DaoManagerException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public it.iccu.sbn.ejb.vo.acquisizioni.TitoloACQAreeIsbdVO getAreeIsbdTitolo( java.lang.String bidPassato )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.persistence.dao.exception.DaoManagerException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaSuggerimenti( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppSuggerimentoVO ricercaSuggerimenti )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppSuggerimentoVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppSuggerimentoVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaSuggerimentoVO( it.iccu.sbn.ejb.vo.acquisizioni.SuggerimentoVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaSuggerimenti( java.util.List listaSuggerimenti )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciSuggerimento( it.iccu.sbn.ejb.vo.acquisizioni.SuggerimentoVO suggerimento )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaSuggerimento( it.iccu.sbn.ejb.vo.acquisizioni.SuggerimentoVO suggerimento )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaSuggerimento( it.iccu.sbn.ejb.vo.acquisizioni.SuggerimentoVO suggerimento )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaConfigurazione( it.iccu.sbn.ejb.vo.acquisizioni.ConfigurazioneBOVO configurazione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public it.iccu.sbn.ejb.vo.acquisizioni.ConfigurazioneBOVO loadConfigurazione( it.iccu.sbn.ejb.vo.acquisizioni.ConfigurazioneBOVO configurazione )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public it.iccu.sbn.ejb.vo.acquisizioni.ConfigurazioneORDVO loadConfigurazioneOrdini( it.iccu.sbn.ejb.vo.acquisizioni.ConfigurazioneORDVO configurazioneORD )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaConfigurazioneOrdini( it.iccu.sbn.ejb.vo.acquisizioni.ConfigurazioneORDVO configurazioneORD )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaDocumenti( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppDocumentoVO ricercaDocumenti )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppDocumentoVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppDocumentoVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaDocumentoVO( it.iccu.sbn.ejb.vo.acquisizioni.DocumentoVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaDocumenti( java.util.List listaDocumenti )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaDocumento( it.iccu.sbn.ejb.vo.acquisizioni.DocumentoVO documento )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaGare( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppGaraVO ricercaGare )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppGaraVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppGaraVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaGaraVO( it.iccu.sbn.ejb.vo.acquisizioni.GaraVO oggettoVO )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaGare( java.util.List listaGare )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaGara( it.iccu.sbn.ejb.vo.acquisizioni.GaraVO gara )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List gestioneStampato( java.util.List listaOggetti, java.lang.String tipoOggetti,java.lang.String bo )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List costruisciCatenaRinnovati(it.iccu.sbn.ejb.vo.acquisizioni.common.StrutturaTerna ordRinn, java.lang.String codBibl)
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;




   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean gestioneStampaOrdini( java.util.List listaOggetti, java.util.List idList, java.lang.String tipoOggetti, java.lang.String utente, java.lang.String bo )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;



   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciGara( it.iccu.sbn.ejb.vo.acquisizioni.GaraVO gara )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaGara( it.iccu.sbn.ejb.vo.acquisizioni.GaraVO gara )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaFornitore( it.iccu.sbn.ejb.vo.acquisizioni.FornitoreVO fornitore )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaOfferte( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppOffertaFornitoreVO ricercaOfferte )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaListaSuppOffertaFornitoreVO( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppOffertaFornitoreVO oggettoLista )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void ValidaRicercaOfferte( java.util.List listaOfferte )
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void migrazioneCStoSBNWEBcateneRinnoviBis()
      throws it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaCambiHib( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppCambioVO ricercaCambi )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciCambioHib( it.iccu.sbn.ejb.vo.acquisizioni.CambioVO cambio )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaCambioHib( it.iccu.sbn.ejb.vo.acquisizioni.CambioVO cambio )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaCambioHib( it.iccu.sbn.ejb.vo.acquisizioni.CambioVO cambio )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaSezioniHib( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppSezioneVO ricercaSezioni )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaSezioneHib( it.iccu.sbn.ejb.vo.acquisizioni.SezioneVO sezione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaSezioneHib( it.iccu.sbn.ejb.vo.acquisizioni.SezioneVO sezione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciSezioneHib( it.iccu.sbn.ejb.vo.acquisizioni.SezioneVO sezione )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getRicercaListaFornitoriHib( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppFornitoreVO ricercaFornitori )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean modificaFornitoreHib( it.iccu.sbn.ejb.vo.acquisizioni.FornitoreVO fornitore )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean cancellaFornitoreHib( it.iccu.sbn.ejb.vo.acquisizioni.FornitoreVO fornitore )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DataException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public boolean inserisciFornitoreHib( it.iccu.sbn.ejb.vo.acquisizioni.FornitoreVO fornitore )
      throws org.hibernate.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppFatturaVO gestioneFatturaDaDocFisico( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppFatturaVO ricercaFatture )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getInventariOrdineRilegatura( it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppOrdiniVO ricercaInvOrd )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List ripartoSpese (it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppSpeseVO criteriRiparto)
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List statisticheTempi (it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppSpeseVO criteriRiparto)
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List impostaBuoniOrdineDaStampare(it.iccu.sbn.ejb.vo.acquisizioni.ConfigurazioneBOVO configurazione, java.util.List listaOggetti, java.lang.String tipoOggetti, Boolean ristampa, java.lang.String ticket, java.lang.String utente, java.lang.String denoBibl )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public List<SchedaPeriodicoVO> picosPeriodici(java.lang.String kbibl, java.lang.String  kordi, java.lang.String  kanno )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public List<SchedaPeriodicoVO> picosPeriodiciInv(java.lang.String kbibl, java.lang.String  kinv, java.lang.String kserie )
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public List<SchedaInventarioVO> picosPeriodiciAskInv(String kbibl, String kordi, String kanno, String tipomat, String tipocirc, String precis, String valore, Boolean flacoll, String consisDoc, int annoBil, String tipoPrezzo, String prezzoBil, String kserie, String ticket)
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public  int  ValidaPreRicercaOrdini (it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppOrdiniVO ricercaOrdini)
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public  FornitoreVO  getFornitore (String codPolo, String codBib, String codFornitore, String descr, String ticket)
      throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

   public CommandResultVO invoke(CommandInvokeVO command) throws RemoteException, ValidationException, ApplicationException;

   public int countRigheFatturaOrdine(OrdiniVO ordine) throws RemoteException, SbnBaseException;

}

