/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.acquisizioni;

import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.exception.ResourceNotFoundException;
import it.iccu.sbn.ejb.exception.ValidationException;
import it.iccu.sbn.ejb.vo.acquisizioni.AdeguamentoCalcoliVO;
import it.iccu.sbn.ejb.vo.acquisizioni.ListaSuppFatturaVO;
import it.iccu.sbn.ejb.vo.acquisizioni.OperazioneSuOrdiniMassivaVO;
import it.iccu.sbn.ejb.vo.acquisizioni.SchedaInventarioInputVO;

import java.rmi.RemoteException;
import java.util.List;

import javax.ejb.EJBObject;

/**
 * Remote interface for AcquisizioniBMT.
 * @generated
 * @wtp generated
 */
public interface AcquisizioniBMT extends EJBObject {

		/**
	    * <!-- begin-xdoclet-definition -->
	    * @throws ResourceNotFoundException
	    * @throws ApplicationException
	    * @throws ValidationException
	    * @generated //TODO: Must provide implementation for bean create stub    */
		public it.iccu.sbn.periodici.vo.SchedaInventarioVO picosRinnovoOrdine( OperazioneSuOrdiniMassivaVO operaz, SchedaInventarioInputVO passaggioDati, String ticket )
	      throws ResourceNotFoundException, ApplicationException, ValidationException, RemoteException;

		/**
	    * <!-- begin-xdoclet-definition -->
	    * @throws ResourceNotFoundException
	    * @throws ApplicationException
	    * @throws ValidationException
	    * @generated //TODO: Must provide implementation for bean create stub    */
	   public OperazioneSuOrdiniMassivaVO gestioneDifferitaOperazioniSuOrdineMassiva( OperazioneSuOrdiniMassivaVO operaz)
	      throws ResourceNotFoundException, ApplicationException, ValidationException, RemoteException;

		/**
	    * <!-- begin-xdoclet-definition -->
	    * @throws ResourceNotFoundException
	    * @throws ApplicationException
	    * @throws ValidationException
	    * @generated //TODO: Must provide implementation for bean create stub    */
	   public boolean getFusioneCollane(String bidOld, String bidNew, String firmaUtente)
	      throws ResourceNotFoundException, ApplicationException, ValidationException, RemoteException;

	   /**
	    * <!-- begin-xdoclet-definition -->
	    * @throws ResourceNotFoundException
	    * @throws ApplicationException
	    * @throws ValidationException
	    * @generated //TODO: Must provide implementation for bean create stub    */
		public AdeguamentoCalcoliVO adeguaCalcoli (AdeguamentoCalcoliVO adeguamentoCalcoliVO)
	      throws ResourceNotFoundException, ApplicationException, ValidationException, RemoteException;

		   /**
		    * <!-- begin-xdoclet-definition -->
		    * @throws ResourceNotFoundException
		    * @throws ApplicationException
		    * @throws ValidationException
		    * @generated //TODO: Must provide implementation for bean create stub    */
		   public List getRicercaListaFatture( ListaSuppFatturaVO ricercaFatture )
		      throws ResourceNotFoundException, ApplicationException, ValidationException, RemoteException;

		public String calcolaCartName(String ticket, String codPolo, String codBib, String cd_bib_google)
			throws ApplicationException, RemoteException;

}

