/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.acquisizioni;

/**
 * Home interface for Acquisizioni.
 * @generated
 * @wtp generated
 */
public interface AcquisizioniHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Acquisizioni";
   public static final String JNDI_NAME="sbnWeb/Acquisizioni";

   public it.iccu.sbn.ejb.domain.acquisizioni.Acquisizioni create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
