/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.acquisizioni;

/**
 * Session layer for ServiziDocumentoFisico.
 * @generated
 * @wtp generated
 */
public class AcquisizioniBMTSession
   extends it.iccu.sbn.ejb.domain.acquisizioni.AcquisizioniBMTBean
   implements javax.ejb.SessionBean
{
   /**
	 * 
	 */
	private static final long serialVersionUID = -4806275778849260364L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbRemove()
   {
   }

}
