/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package it.finsiel.sbn.polo.orm.viste;

import it.finsiel.sbn.polo.orm.KeyParameter;
import it.finsiel.sbn.polo.orm.OggettoServerSbnMarc;

import java.io.Serializable;


/**
 * Vl_sog_tit_bib generated by MyEclipse - Hibernate Tools
 */

public class Vl_the_tit_bib extends OggettoServerSbnMarc implements Serializable {

	private static final long serialVersionUID = -567188981843834538L;


	public boolean equals(Object aObj) {
		if (aObj == null)
			return false;
		if (!(aObj instanceof Vl_the_tit_bib))
			return false;
		Vl_the_tit_bib vl_the_tit_bib = (Vl_the_tit_bib)aObj;
		if (getBID() != null && !getBID().equals(vl_the_tit_bib.getBID()))
			return false;
		if (getDID() != null && !getDID().equals(vl_the_tit_bib.getDID()))
			return false;
		if (getCD_POLO() != null && !getCD_POLO().equals(vl_the_tit_bib.getCD_POLO()))
			return false;
		if (getCD_BIBLIOTECA() != null && !getCD_BIBLIOTECA().equals(vl_the_tit_bib.getCD_BIBLIOTECA()))
			return false;
		return true;
	}

	public int hashCode() {
		int hashcode = 0;
		hashcode = hashcode + getBID().hashCode();
		hashcode = hashcode + getDID().hashCode();
		hashcode = hashcode + getCD_POLO().hashCode();
		hashcode = hashcode + getCD_BIBLIOTECA().hashCode();
		return hashcode;
	}
	public String toString() {
		return String.valueOf(getBID() + " " + getDID()+ " " + getCD_POLO()+ " " + getCD_BIBLIOTECA());
	}

    // Fields

     private String BID;
     private String DID;
     private String CD_POLO;
     private String CD_BIBLIOTECA;
     private String CD_THE;


    // Constructors

    /** default constructor */
    public Vl_the_tit_bib() {
    }


    /** full constructor */
    public Vl_the_tit_bib(String BID, String DID, String CD_POLO, String CD_BIBLIOTECA, String CD_THE) {
        this.BID = BID;
        this.DID = DID;
        this.CD_POLO = CD_POLO;
        this.CD_BIBLIOTECA = CD_BIBLIOTECA;
        this.CD_THE = CD_THE;
    }


    // Property accessors

    public String getBID() {
        return this.BID;
    }

    public void setBID(String value) {
        this.BID = value;
		this.settaParametro(KeyParameter.XXXbid, value);

    }

    public String getDID() {
        return this.DID;
    }

    public void setDID(String value) {
        this.DID = value;
		this.settaParametro(KeyParameter.XXXdid, value);
    }

    public String getCD_POLO() {
        return this.CD_POLO;
    }

    public void setCD_POLO(String value) {
        this.CD_POLO = value;
		this.settaParametro(KeyParameter.XXXcd_polo, value);
    }

    public String getCD_BIBLIOTECA() {
        return this.CD_BIBLIOTECA;
    }

    public void setCD_BIBLIOTECA(String value) {
        this.CD_BIBLIOTECA = value;
		this.settaParametro(KeyParameter.XXXcd_biblioteca, value);
    }

    public String getCD_THE() {
        return this.CD_THE;
    }

    public void setCD_THE(String value) {
        this.CD_THE = value;
		this.settaParametro(KeyParameter.XXXcd_the, value);
    }









}
