/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.01 at 01:17:47 PM CEST
//


package it.iccu.sbn.vo.xml.binding.ill.apdu;

import it.iccu.sbn.ejb.vo.SerializableVO;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnswerType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AnswerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Conditional" type="{}ConditionalType"/>
 *         &lt;element ref="{}Retry"/>
 *         &lt;element ref="{}Unfilled"/>
 *         &lt;element ref="{}Location-provider"/>
 *         &lt;element ref="{}Will-supply"/>
 *         &lt;element ref="{}Hold-placed"/>
 *         &lt;element name="Estimate" type="{}EstimateType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnswerType", propOrder = {
    "conditional",
    "retry",
    "unfilled",
    "locationProvider",
    "willSupply",
    "holdPlaced",
    "estimate"
})
public class AnswerType
    extends SerializableVO
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Conditional")
    protected ConditionalType conditional;
    @XmlElement(name = "Retry")
    protected Retry retry;
    @XmlElement(name = "Unfilled")
    protected Unfilled unfilled;
    @XmlElement(name = "Location-provider")
    protected LocationProvider locationProvider;
    @XmlElement(name = "Will-supply")
    protected WillSupply willSupply;
    @XmlElement(name = "Hold-placed")
    protected HoldPlaced holdPlaced;
    @XmlElement(name = "Estimate")
    protected EstimateType estimate;

    /**
     * Gets the value of the conditional property.
     *
     * @return
     *     possible object is
     *     {@link ConditionalType }
     *
     */
    public ConditionalType getConditional() {
        return conditional;
    }

    /**
     * Sets the value of the conditional property.
     *
     * @param value
     *     allowed object is
     *     {@link ConditionalType }
     *
     */
    public void setConditional(ConditionalType value) {
        this.conditional = value;
    }

    /**
     * Gets the value of the retry property.
     *
     * @return
     *     possible object is
     *     {@link Retry }
     *
     */
    public Retry getRetry() {
        return retry;
    }

    /**
     * Sets the value of the retry property.
     *
     * @param value
     *     allowed object is
     *     {@link Retry }
     *
     */
    public void setRetry(Retry value) {
        this.retry = value;
    }

    /**
     * Gets the value of the unfilled property.
     *
     * @return
     *     possible object is
     *     {@link Unfilled }
     *
     */
    public Unfilled getUnfilled() {
        return unfilled;
    }

    /**
     * Sets the value of the unfilled property.
     *
     * @param value
     *     allowed object is
     *     {@link Unfilled }
     *
     */
    public void setUnfilled(Unfilled value) {
        this.unfilled = value;
    }

    /**
     * Gets the value of the locationProvider property.
     *
     * @return
     *     possible object is
     *     {@link LocationProvider }
     *
     */
    public LocationProvider getLocationProvider() {
        return locationProvider;
    }

    /**
     * Sets the value of the locationProvider property.
     *
     * @param value
     *     allowed object is
     *     {@link LocationProvider }
     *
     */
    public void setLocationProvider(LocationProvider value) {
        this.locationProvider = value;
    }

    /**
     * Gets the value of the willSupply property.
     *
     * @return
     *     possible object is
     *     {@link WillSupply }
     *
     */
    public WillSupply getWillSupply() {
        return willSupply;
    }

    /**
     * Sets the value of the willSupply property.
     *
     * @param value
     *     allowed object is
     *     {@link WillSupply }
     *
     */
    public void setWillSupply(WillSupply value) {
        this.willSupply = value;
    }

    /**
     * Gets the value of the holdPlaced property.
     *
     * @return
     *     possible object is
     *     {@link HoldPlaced }
     *
     */
    public HoldPlaced getHoldPlaced() {
        return holdPlaced;
    }

    /**
     * Sets the value of the holdPlaced property.
     *
     * @param value
     *     allowed object is
     *     {@link HoldPlaced }
     *
     */
    public void setHoldPlaced(HoldPlaced value) {
        this.holdPlaced = value;
    }

    /**
     * Gets the value of the estimate property.
     *
     * @return
     *     possible object is
     *     {@link EstimateType }
     *
     */
    public EstimateType getEstimate() {
        return estimate;
    }

    /**
     * Sets the value of the estimate property.
     *
     * @param value
     *     allowed object is
     *     {@link EstimateType }
     *
     */
    public void setEstimate(EstimateType value) {
        this.estimate = value;
    }

}
