/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.11.11 at 12:42:47 PM CET
//


package it.iccu.sbn.vo.xml.binding.ill.apdu;

import it.iccu.sbn.ejb.vo.SerializableVO;
import it.iccu.sbn.servizi.ill.api.ILLBaseAction;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ILL_RequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ILL_RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Transaction-Id"/>
 *         &lt;element name="Service-date-time" type="{}ServiceDateTimeType"/>
 *         &lt;element ref="{}Requester-Id"/>
 *         &lt;element ref="{}Responder-Id"/>
 *         &lt;element ref="{}Delivery-address" minOccurs="0"/>
 *         &lt;element ref="{}Delivery-service" minOccurs="0"/>
 *         &lt;element ref="{}Requester-optional-messages" minOccurs="0"/>
 *         &lt;element ref="{}Supply-medium-type" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Place-on-hold" minOccurs="0"/>
 *         &lt;element name="Client-Id" type="{}ClientIdType"/>
 *         &lt;element ref="{}Item-Id"/>
 *         &lt;element ref="{}Date-requester" minOccurs="0"/>
 *         &lt;element ref="{}Need-before-date" minOccurs="0"/>
 *         &lt;element ref="{}Expiry-date" minOccurs="0"/>
 *         &lt;element name="Cost-info-type" type="{}CostInfoType" minOccurs="0"/>
 *         &lt;element ref="{}Copyright-compliance" minOccurs="0"/>
 *         &lt;element ref="{}Requester-note" minOccurs="0"/>
 *         &lt;element ref="{}Current-state" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ILL-SERVICE-TYPE" use="required" type="{}ILLServiceType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ILL_RequestType", propOrder = {
    "transactionId",
    "serviceDateTime",
    "requesterId",
    "responderId",
    "deliveryAddress",
    "deliveryService",
    "requesterOptionalMessages",
    "supplyMediumType",
    "placeOnHold",
    "clientId",
    "itemId",
    "dateRequester",
    "needBeforeDate",
    "expiryDate",
    "costInfoType",
    "copyrightCompliance",
    "requesterNote",
    "currentState"
})
public class ILLRequestType
    extends SerializableVO
    implements Serializable, ILLBaseAction
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Transaction-Id", required = true)
    protected TransactionIdType transactionId;
    @XmlElement(name = "Service-date-time", required = true)
    protected ServiceDateTimeType serviceDateTime;
    @XmlElement(name = "Requester-Id", required = true)
    protected String requesterId;
    @XmlElement(name = "Responder-Id", required = true)
    protected String responderId;
    @XmlElement(name = "Delivery-address")
    protected DeliveryAddressType deliveryAddress;
    @XmlElement(name = "Delivery-service")
    protected DeliveryService deliveryService;
    @XmlElement(name = "Requester-optional-messages")
    protected RequesterOptionalMessages requesterOptionalMessages;
    @XmlElement(name = "Supply-medium-type", required = true)
    protected List<SupplyMediumTypeType> supplyMediumType;
    @XmlElement(name = "Place-on-hold")
    protected PlaceOnHold placeOnHold;
    @XmlElement(name = "Client-Id", required = true)
    protected ClientIdType clientId;
    @XmlElement(name = "Item-Id", required = true)
    protected ItemIdType itemId;
    @XmlElement(name = "Date-requester")
    protected DateRequester dateRequester;
    @XmlElement(name = "Need-before-date")
    protected NeedBeforeDate needBeforeDate;
    @XmlElement(name = "Expiry-date")
    protected ExpiryDate expiryDate;
    @XmlElement(name = "Cost-info-type")
    protected CostInfoType costInfoType;
    @XmlElement(name = "Copyright-compliance")
    protected String copyrightCompliance;
    @XmlElement(name = "Requester-note")
    protected RequesterNote requesterNote;
    @XmlElement(name = "Current-state")
    protected CurrentState currentState;
    @XmlAttribute(name = "ILL-SERVICE-TYPE", required = true)
    protected ILLServiceType illservicetype;

    /**
     * Gets the value of the transactionId property.
     *
     * @return
     *     possible object is
     *     {@link TransactionIdType }
     *
     */
    public TransactionIdType getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     *
     * @param value
     *     allowed object is
     *     {@link TransactionIdType }
     *
     */
    public void setTransactionId(TransactionIdType value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the serviceDateTime property.
     *
     * @return
     *     possible object is
     *     {@link ServiceDateTimeType }
     *
     */
    public ServiceDateTimeType getServiceDateTime() {
        return serviceDateTime;
    }

    /**
     * Sets the value of the serviceDateTime property.
     *
     * @param value
     *     allowed object is
     *     {@link ServiceDateTimeType }
     *
     */
    public void setServiceDateTime(ServiceDateTimeType value) {
        this.serviceDateTime = value;
    }

    /**
     * Gets the value of the requesterId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRequesterId() {
        return requesterId;
    }

    /**
     * Sets the value of the requesterId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRequesterId(String value) {
        this.requesterId = value;
    }

    /**
     * Gets the value of the responderId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResponderId() {
        return responderId;
    }

    /**
     * Sets the value of the responderId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResponderId(String value) {
        this.responderId = value;
    }

    /**
     * Gets the value of the deliveryAddress property.
     *
     * @return
     *     possible object is
     *     {@link DeliveryAddressType }
     *
     */
    public DeliveryAddressType getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * Sets the value of the deliveryAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link DeliveryAddressType }
     *
     */
    public void setDeliveryAddress(DeliveryAddressType value) {
        this.deliveryAddress = value;
    }

    /**
     * Gets the value of the deliveryService property.
     *
     * @return
     *     possible object is
     *     {@link DeliveryService }
     *
     */
    public DeliveryService getDeliveryService() {
        return deliveryService;
    }

    /**
     * Sets the value of the deliveryService property.
     *
     * @param value
     *     allowed object is
     *     {@link DeliveryService }
     *
     */
    public void setDeliveryService(DeliveryService value) {
        this.deliveryService = value;
    }

    /**
     * Gets the value of the requesterOptionalMessages property.
     *
     * @return
     *     possible object is
     *     {@link RequesterOptionalMessages }
     *
     */
    public RequesterOptionalMessages getRequesterOptionalMessages() {
        return requesterOptionalMessages;
    }

    /**
     * Sets the value of the requesterOptionalMessages property.
     *
     * @param value
     *     allowed object is
     *     {@link RequesterOptionalMessages }
     *
     */
    public void setRequesterOptionalMessages(RequesterOptionalMessages value) {
        this.requesterOptionalMessages = value;
    }

    /**
     * Gets the value of the supplyMediumType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplyMediumType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplyMediumType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplyMediumTypeType }
     *
     *
     */
    public List<SupplyMediumTypeType> getSupplyMediumType() {
        if (supplyMediumType == null) {
            supplyMediumType = new ArrayList<SupplyMediumTypeType>();
        }
        return this.supplyMediumType;
    }

    /**
     * Gets the value of the placeOnHold property.
     *
     * @return
     *     possible object is
     *     {@link PlaceOnHold }
     *
     */
    public PlaceOnHold getPlaceOnHold() {
        return placeOnHold;
    }

    /**
     * Sets the value of the placeOnHold property.
     *
     * @param value
     *     allowed object is
     *     {@link PlaceOnHold }
     *
     */
    public void setPlaceOnHold(PlaceOnHold value) {
        this.placeOnHold = value;
    }

    /**
     * Gets the value of the clientId property.
     *
     * @return
     *     possible object is
     *     {@link ClientIdType }
     *
     */
    public ClientIdType getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     *
     * @param value
     *     allowed object is
     *     {@link ClientIdType }
     *
     */
    public void setClientId(ClientIdType value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the itemId property.
     *
     * @return
     *     possible object is
     *     {@link ItemIdType }
     *
     */
    public ItemIdType getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     *
     * @param value
     *     allowed object is
     *     {@link ItemIdType }
     *
     */
    public void setItemId(ItemIdType value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the dateRequester property.
     *
     * @return
     *     possible object is
     *     {@link DateRequester }
     *
     */
    public DateRequester getDateRequester() {
        return dateRequester;
    }

    /**
     * Sets the value of the dateRequester property.
     *
     * @param value
     *     allowed object is
     *     {@link DateRequester }
     *
     */
    public void setDateRequester(DateRequester value) {
        this.dateRequester = value;
    }

    /**
     * Gets the value of the needBeforeDate property.
     *
     * @return
     *     possible object is
     *     {@link NeedBeforeDate }
     *
     */
    public NeedBeforeDate getNeedBeforeDate() {
        return needBeforeDate;
    }

    /**
     * Sets the value of the needBeforeDate property.
     *
     * @param value
     *     allowed object is
     *     {@link NeedBeforeDate }
     *
     */
    public void setNeedBeforeDate(NeedBeforeDate value) {
        this.needBeforeDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     *
     * @return
     *     possible object is
     *     {@link ExpiryDate }
     *
     */
    public ExpiryDate getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     *
     * @param value
     *     allowed object is
     *     {@link ExpiryDate }
     *
     */
    public void setExpiryDate(ExpiryDate value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the costInfoType property.
     *
     * @return
     *     possible object is
     *     {@link CostInfoType }
     *
     */
    public CostInfoType getCostInfoType() {
        return costInfoType;
    }

    /**
     * Sets the value of the costInfoType property.
     *
     * @param value
     *     allowed object is
     *     {@link CostInfoType }
     *
     */
    public void setCostInfoType(CostInfoType value) {
        this.costInfoType = value;
    }

    /**
     * Gets the value of the copyrightCompliance property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCopyrightCompliance() {
        return copyrightCompliance;
    }

    /**
     * Sets the value of the copyrightCompliance property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCopyrightCompliance(String value) {
        this.copyrightCompliance = value;
    }

    /**
     * Gets the value of the requesterNote property.
     *
     * @return
     *     possible object is
     *     {@link RequesterNote }
     *
     */
    public RequesterNote getRequesterNote() {
        return requesterNote;
    }

    /**
     * Sets the value of the requesterNote property.
     *
     * @param value
     *     allowed object is
     *     {@link RequesterNote }
     *
     */
    public void setRequesterNote(RequesterNote value) {
        this.requesterNote = value;
    }

    /**
     * Gets the value of the currentState property.
     *
     * @return
     *     possible object is
     *     {@link CurrentState }
     *
     */
    public CurrentState getCurrentState() {
        return currentState;
    }

    /**
     * Sets the value of the currentState property.
     *
     * @param value
     *     allowed object is
     *     {@link CurrentState }
     *
     */
    public void setCurrentState(CurrentState value) {
        this.currentState = value;
    }

    /**
     * Gets the value of the illservicetype property.
     *
     * @return
     *     possible object is
     *     {@link ILLServiceType }
     *
     */
    public ILLServiceType getILLSERVICETYPE() {
        return illservicetype;
    }

    /**
     * Sets the value of the illservicetype property.
     *
     * @param value
     *     allowed object is
     *     {@link ILLServiceType }
     *
     */
    public void setILLSERVICETYPE(ILLServiceType value) {
        this.illservicetype = value;
    }

}
