/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.21 at 02:52:06 PM CEST
//


package it.iccu.sbn.vo.xml.binding.ill.apdu;

import it.iccu.sbn.ejb.vo.SerializableVO;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Item-IdType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Item-IdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Item-type" minOccurs="0"/>
 *         &lt;element ref="{}Medium-type" minOccurs="0"/>
 *         &lt;element ref="{}Location-note" minOccurs="0"/>
 *         &lt;element ref="{}Author" minOccurs="0"/>
 *         &lt;element ref="{}Title"/>
 *         &lt;element ref="{}Sub-title" minOccurs="0"/>
 *         &lt;element ref="{}Sponsoring-body" minOccurs="0"/>
 *         &lt;element ref="{}Place-of-publication" minOccurs="0"/>
 *         &lt;element ref="{}Publisher" minOccurs="0"/>
 *         &lt;element ref="{}Series-title-number" minOccurs="0"/>
 *         &lt;element ref="{}Volume-issue" minOccurs="0"/>
 *         &lt;element ref="{}Year-issue" minOccurs="0"/>
 *         &lt;element ref="{}Issue" minOccurs="0"/>
 *         &lt;element ref="{}Edition" minOccurs="0"/>
 *         &lt;element ref="{}Publication-date" minOccurs="0"/>
 *         &lt;element ref="{}Author-of-article" minOccurs="0"/>
 *         &lt;element ref="{}Title-of-article" minOccurs="0"/>
 *         &lt;element ref="{}Pagination" minOccurs="0"/>
 *         &lt;element ref="{}National-bibliografic-number" minOccurs="0"/>
 *         &lt;element name="Standard-number" type="{}StandardNumberType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Verification-reference-source" minOccurs="0"/>
 *         &lt;element ref="{}Additional-no-letters" minOccurs="0"/>
 *         &lt;element ref="{}System-no" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Item-IdType", propOrder = {
    "itemType",
    "mediumType",
    "locationNote",
    "author",
    "title",
    "subTitle",
    "sponsoringBody",
    "placeOfPublication",
    "publisher",
    "seriesTitleNumber",
    "volumeIssue",
    "yearIssue",
    "issue",
    "edition",
    "publicationDate",
    "authorOfArticle",
    "titleOfArticle",
    "pagination",
    "nationalBibliograficNumber",
    "standardNumber",
    "verificationReferenceSource",
    "additionalNoLetters",
    "systemNo"
})
public class ItemIdType
    extends SerializableVO
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Item-type")
    protected ItemType itemType;
    @XmlElement(name = "Medium-type")
    protected MediumType mediumType;
    @XmlElement(name = "Location-note")
    protected String locationNote;
    @XmlElement(name = "Author")
    protected String author;
    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "Sub-title")
    protected String subTitle;
    @XmlElement(name = "Sponsoring-body")
    protected String sponsoringBody;
    @XmlElement(name = "Place-of-publication")
    protected String placeOfPublication;
    @XmlElement(name = "Publisher")
    protected String publisher;
    @XmlElement(name = "Series-title-number")
    protected String seriesTitleNumber;
    @XmlElement(name = "Volume-issue")
    protected String volumeIssue;
    @XmlElement(name = "Year-issue")
    protected String yearIssue;
    @XmlElement(name = "Issue")
    protected String issue;
    @XmlElement(name = "Edition")
    protected String edition;
    @XmlElement(name = "Publication-date")
    protected String publicationDate;
    @XmlElement(name = "Author-of-article")
    protected String authorOfArticle;
    @XmlElement(name = "Title-of-article")
    protected String titleOfArticle;
    @XmlElement(name = "Pagination")
    protected String pagination;
    @XmlElement(name = "National-bibliografic-number")
    protected String nationalBibliograficNumber;
    @XmlElement(name = "Standard-number")
    protected List<StandardNumberType> standardNumber;
    @XmlElement(name = "Verification-reference-source")
    protected String verificationReferenceSource;
    @XmlElement(name = "Additional-no-letters")
    protected String additionalNoLetters;
    @XmlElement(name = "System-no")
    protected String systemNo;

    /**
     * Gets the value of the itemType property.
     *
     * @return
     *     possible object is
     *     {@link ItemType }
     *
     */
    public ItemType getItemType() {
        return itemType;
    }

    /**
     * Sets the value of the itemType property.
     *
     * @param value
     *     allowed object is
     *     {@link ItemType }
     *
     */
    public void setItemType(ItemType value) {
        this.itemType = value;
    }

    /**
     * Gets the value of the mediumType property.
     *
     * @return
     *     possible object is
     *     {@link MediumType }
     *
     */
    public MediumType getMediumType() {
        return mediumType;
    }

    /**
     * Sets the value of the mediumType property.
     *
     * @param value
     *     allowed object is
     *     {@link MediumType }
     *
     */
    public void setMediumType(MediumType value) {
        this.mediumType = value;
    }

    /**
     * Gets the value of the locationNote property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLocationNote() {
        return locationNote;
    }

    /**
     * Sets the value of the locationNote property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLocationNote(String value) {
        this.locationNote = value;
    }

    /**
     * Gets the value of the author property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the subTitle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * Sets the value of the subTitle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubTitle(String value) {
        this.subTitle = value;
    }

    /**
     * Gets the value of the sponsoringBody property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSponsoringBody() {
        return sponsoringBody;
    }

    /**
     * Sets the value of the sponsoringBody property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSponsoringBody(String value) {
        this.sponsoringBody = value;
    }

    /**
     * Gets the value of the placeOfPublication property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlaceOfPublication() {
        return placeOfPublication;
    }

    /**
     * Sets the value of the placeOfPublication property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlaceOfPublication(String value) {
        this.placeOfPublication = value;
    }

    /**
     * Gets the value of the publisher property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPublisher(String value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the seriesTitleNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSeriesTitleNumber() {
        return seriesTitleNumber;
    }

    /**
     * Sets the value of the seriesTitleNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSeriesTitleNumber(String value) {
        this.seriesTitleNumber = value;
    }

    /**
     * Gets the value of the volumeIssue property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVolumeIssue() {
        return volumeIssue;
    }

    /**
     * Sets the value of the volumeIssue property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVolumeIssue(String value) {
        this.volumeIssue = value;
    }

    /**
     * Gets the value of the yearIssue property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getYearIssue() {
        return yearIssue;
    }

    /**
     * Sets the value of the yearIssue property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setYearIssue(String value) {
        this.yearIssue = value;
    }

    /**
     * Gets the value of the issue property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIssue() {
        return issue;
    }

    /**
     * Sets the value of the issue property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIssue(String value) {
        this.issue = value;
    }

    /**
     * Gets the value of the edition property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEdition(String value) {
        this.edition = value;
    }

    /**
     * Gets the value of the publicationDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPublicationDate(String value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the authorOfArticle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAuthorOfArticle() {
        return authorOfArticle;
    }

    /**
     * Sets the value of the authorOfArticle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAuthorOfArticle(String value) {
        this.authorOfArticle = value;
    }

    /**
     * Gets the value of the titleOfArticle property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitleOfArticle() {
        return titleOfArticle;
    }

    /**
     * Sets the value of the titleOfArticle property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitleOfArticle(String value) {
        this.titleOfArticle = value;
    }

    /**
     * Gets the value of the pagination property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPagination(String value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the nationalBibliograficNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNationalBibliograficNumber() {
        return nationalBibliograficNumber;
    }

    /**
     * Sets the value of the nationalBibliograficNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNationalBibliograficNumber(String value) {
        this.nationalBibliograficNumber = value;
    }

    /**
     * Gets the value of the standardNumber property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardNumber property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardNumber().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardNumberType }
     *
     *
     */
    public List<StandardNumberType> getStandardNumber() {
        if (standardNumber == null) {
            standardNumber = new ArrayList<StandardNumberType>();
        }
        return this.standardNumber;
    }

    /**
     * Gets the value of the verificationReferenceSource property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVerificationReferenceSource() {
        return verificationReferenceSource;
    }

    /**
     * Sets the value of the verificationReferenceSource property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVerificationReferenceSource(String value) {
        this.verificationReferenceSource = value;
    }

    /**
     * Gets the value of the additionalNoLetters property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAdditionalNoLetters() {
        return additionalNoLetters;
    }

    /**
     * Sets the value of the additionalNoLetters property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAdditionalNoLetters(String value) {
        this.additionalNoLetters = value;
    }

    /**
     * Gets the value of the systemNo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSystemNo() {
        return systemNo;
    }

    /**
     * Sets the value of the systemNo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSystemNo(String value) {
        this.systemNo = value;
    }

}
