/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.01 at 01:17:47 PM CEST
//


package it.iccu.sbn.vo.xml.binding.ill.apdu;

import it.iccu.sbn.ejb.vo.SerializableVO;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{}Date-shipped"/>
 *         &lt;element ref="{}Date-due"/>
 *         &lt;element ref="{}Chargeable-units" minOccurs="0"/>
 *         &lt;element name="Cost" type="{}CostType" minOccurs="0"/>
 *         &lt;element name="Shipped-via" type="{}ShippedViaType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dateShipped",
    "dateDue",
    "chargeableUnits",
    "cost",
    "shippedVia"
})
@XmlRootElement(name = "Supply-details")
public class SupplyDetails
    extends SerializableVO
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Date-shipped")
    protected DateShipped dateShipped;
    @XmlElement(name = "Date-due")
    protected DateDue dateDue;
    @XmlElement(name = "Chargeable-units")
    protected String chargeableUnits;
    @XmlElement(name = "Cost")
    protected CostType cost;
    @XmlElement(name = "Shipped-via")
    protected ShippedViaType shippedVia;

    /**
     * Gets the value of the dateShipped property.
     *
     * @return
     *     possible object is
     *     {@link DateShipped }
     *
     */
    public DateShipped getDateShipped() {
        return dateShipped;
    }

    /**
     * Sets the value of the dateShipped property.
     *
     * @param value
     *     allowed object is
     *     {@link DateShipped }
     *
     */
    public void setDateShipped(DateShipped value) {
        this.dateShipped = value;
    }

    /**
     * Gets the value of the dateDue property.
     *
     * @return
     *     possible object is
     *     {@link DateDue }
     *
     */
    public DateDue getDateDue() {
        return dateDue;
    }

    /**
     * Sets the value of the dateDue property.
     *
     * @param value
     *     allowed object is
     *     {@link DateDue }
     *
     */
    public void setDateDue(DateDue value) {
        this.dateDue = value;
    }

    /**
     * Gets the value of the chargeableUnits property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getChargeableUnits() {
        return chargeableUnits;
    }

    /**
     * Sets the value of the chargeableUnits property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setChargeableUnits(String value) {
        this.chargeableUnits = value;
    }

    /**
     * Gets the value of the cost property.
     *
     * @return
     *     possible object is
     *     {@link CostType }
     *
     */
    public CostType getCost() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     *
     * @param value
     *     allowed object is
     *     {@link CostType }
     *
     */
    public void setCost(CostType value) {
        this.cost = value;
    }

    /**
     * Gets the value of the shippedVia property.
     *
     * @return
     *     possible object is
     *     {@link ShippedViaType }
     *
     */
    public ShippedViaType getShippedVia() {
        return shippedVia;
    }

    /**
     * Sets the value of the shippedVia property.
     *
     * @param value
     *     allowed object is
     *     {@link ShippedViaType }
     *
     */
    public void setShippedVia(ShippedViaType value) {
        this.shippedVia = value;
    }

}
