/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.10.01 at 01:17:47 PM CEST
//


package it.iccu.sbn.vo.xml.binding.ill.apdu;

import it.iccu.sbn.ejb.vo.SerializableVO;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for TransactionIdType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TransactionIdType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="institution-symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name-of-institution" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transaction-group-qualifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transaction-qualifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionIdType", propOrder = {
    "value"
})
public class TransactionIdType
    extends SerializableVO
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlValue
    protected String value;
    @XmlAttribute(name = "institution-symbol")
    protected String institutionSymbol;
    @XmlAttribute(name = "name-of-institution")
    protected String nameOfInstitution;
    @XmlAttribute(name = "transaction-group-qualifier")
    protected String transactionGroupQualifier;
    @XmlAttribute(name = "transaction-qualifier")
    protected String transactionQualifier;

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the institutionSymbol property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInstitutionSymbol() {
        return institutionSymbol;
    }

    /**
     * Sets the value of the institutionSymbol property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInstitutionSymbol(String value) {
        this.institutionSymbol = value;
    }

    /**
     * Gets the value of the nameOfInstitution property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNameOfInstitution() {
        return nameOfInstitution;
    }

    /**
     * Sets the value of the nameOfInstitution property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNameOfInstitution(String value) {
        this.nameOfInstitution = value;
    }

    /**
     * Gets the value of the transactionGroupQualifier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransactionGroupQualifier() {
        return transactionGroupQualifier;
    }

    /**
     * Sets the value of the transactionGroupQualifier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransactionGroupQualifier(String value) {
        this.transactionGroupQualifier = value;
    }

    /**
     * Gets the value of the transactionQualifier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransactionQualifier() {
        return transactionQualifier;
    }

    /**
     * Sets the value of the transactionQualifier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransactionQualifier(String value) {
        this.transactionQualifier = value;
    }

}
