/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.periodici.ejb;

public interface PeriodiciHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Periodici";
   public static final String JNDI_NAME="sbnWeb/Periodici";

   public Periodici create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
