/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.services.acquisizioni;

/**
 * Session layer for ServiziAcquisizioni.
 * @generated
 * @wtp generated
 */
public class ServiziAcquisizioniSession
   extends it.iccu.sbn.ejb.services.acquisizioni.ServiziAcquisizioniBean
   implements javax.ejb.SessionBean
{

	private static final long serialVersionUID = 8166638077043596617L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbRemove()
   {
   }

}
