/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.elaborazioniDifferite.importa;

import it.iccu.sbn.ejb.domain.stampe.SbnStampeBaseRemote;



/**
 * Remote interface for RegistriIngresso.
 * @generated
 * @wtp generated
 */
public interface StampaReportImport
   extends javax.ejb.EJBObject, SbnStampeBaseRemote {}