/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.elaborazioniDifferite.importa;

/**
 * Home interface for Schede.
 * @generated
 * @wtp generated
 */
public interface StampaReportImportHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SBNStampeSchedeOnLine";
   public static final String JNDI_NAME="sbnWeb/SBNStampeSchedeOnLine";

   public StampaReportImport create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
