/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.bibliografica;

/**
 * Home interface for Interrogazione.
 * @generated
 * @wtp generated
 */
public interface InterrogazioneHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Interrogazione";
   public static final String JNDI_NAME="sbnWeb/Interrogazione";

   public it.iccu.sbn.ejb.domain.bibliografica.Interrogazione create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
