/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.bibliografica;

/**
 * Session layer for Interrogazione.
 * @generated
 * @wtp generated
 */
public class InterrogazioneSession
   extends it.iccu.sbn.ejb.domain.bibliografica.InterrogazioneBean
   implements javax.ejb.SessionBean
{
   /**
	 * 
	 */
	private static final long serialVersionUID = -8318587550666608477L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbRemove()
   {
   }

}
