/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.bibliografica;

/**
 * Session layer for Profiler.
 * @generated
 * @wtp generated
 */
public class ProfilerSession
   extends it.iccu.sbn.ejb.domain.bibliografica.ProfilerBean
   implements javax.ejb.SessionBean
{
   /**
	 * 
	 */
	private static final long serialVersionUID = 6572842182560414039L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx)
   {
   }

   public void unsetSessionContext()
   {
   }

   public void ejbRemove()
   {
   }

}
