/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.bibliografica;

import it.iccu.sbn.persistence.dao.exception.DaoManagerException;

import java.rmi.RemoteException;
import java.util.List;

import javax.naming.NamingException;

/**
 * Remote interface for Repertorio.
 * @generated
 * @wtp generated
 */
public interface Repertorio
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @throws NamingException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void bindRepertori()
      throws DaoManagerException, NamingException, RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @throws NamingException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public List getAllRepertori(  )
      throws DaoManagerException, NamingException, RemoteException;

   public void truncate(String ticket) throws RemoteException;

}
