/*
 * Generated by XDoclet - Do not edit!
 */
package it.finsiel.sbn.polo.ejb;

import java.rmi.RemoteException;

import javax.ejb.Local;


/**
 * Remote interface for Profiler.
 * @generated
 * @wtp generated
 */
@Local
public interface Profiler  {
   public final String JNDI_NAME = "sbnMarc/Profiler/local";
/**
    * <!-- begin-xdoclet-definition -->
    * @generated Inizializzazione patrimonio anagrafe amministrazione <br> legge i dati su cui attivare i permessi (tutto in fase iniziale) <br>
    * @param connessione al db
    * @return nessuno    */
   public void init(  )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Verifica se il soggetto richiesto Ã¨ un polo <br> Semplice: Se i primi tre caratteri sono XXX si tratta di un utente fisico creato in fase di amministrazione, altrimenti Ã¨ un codice polo <br>
    * @param codice (polo/gruppo/utente)
    * @return boolean (true=polo, false = no polo)    */
   public boolean isPolo( java.lang.String codice )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Restituisce il codice livello di un utente per uno specifico tipo di materiale    */
   public it.finsiel.sbn.polo.orm.amministrazione.Tbf_par_mat getParametriUtentePerMateriale( java.lang.String codice,java.lang.String tipoMateriale )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Ritorna oggetto parametri utente <br> Torna un oggetto di tipo Tb_parametro Metodo a disposizione dei FACTORING (Sbnmarc e non) <br>
    * @param codice polo
    * @return oggetto complesso con informazioni    */
   public it.finsiel.sbn.polo.orm.amministrazione.Tbf_parametro getTb_parametro( java.lang.String codice )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Restituisce il codice livello di un utente per uno specifico tipo di authority    */
   public it.finsiel.sbn.polo.orm.amministrazione.Tbf_par_auth getParametriUtentePerAuthority( java.lang.String codice,java.lang.String tipoAuthority )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Ritorna oggetto con abilitazioni COMPLETE per gruppo/utente <br> Intuisce dalla composizione del codice ricevuto se si tratta di un utente o di un gruppo di tipo (Polo) Metodo a disposizione dei FACTORING (Sbnmarc e non) Se i primi tre caratteri del codice sono XXX si tratta di un utente della struttura (utilizza I.Diretta o Forms amministrazione) Else si tratta di un polo SBNMARC <br>
    * @param codice (polo/gruppo/utente)
    * @return oggetto complesso con informazioni    */
   public it.finsiel.sbn.polo.factoring.profile.ValidatorContainerObject getAbilitazioni( java.lang.String codice )
      throws RemoteException;

   public it.finsiel.sbn.polo.factoring.profile.ValidatorContainerObject getAbilitazioniPolo( java.lang.String cd_polo )
		      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Informa se l'attivitÃ  per il gruppo/polo richiesto Ã¨ abilitata (VERSIONE CODICE ATTIVITA NUMERICO) <br> Intuisce dalla composizione del codice ricevuto se si tratta di un utente o di un gruppo di tipo (Polo) Metodo a disposizione dei FACTORING (Sbnmarc e non) Se i primi tre caratteri del codice sono XXX si tratta di un utente della struttura (utilizza I.Diretta o Forms amministrazione) Else si tratta di un polo SBNMARC <br>
    * @param codice (polo/gruppo/utente)
    * @param codice attivita
    * @return trovato = true/ non trovato = false    */
   public boolean verificaAttivitaID( java.lang.String codice,java.lang.String codice_attivita )
      throws it.finsiel.sbn.polo.exception.EccezioneSbnDiagnostico, RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Informa se l'attivitÃ  per il gruppo/polo richiesto Ã¨ abilitata <br> Intuisce dalla composizione del codice ricevuto se si tratta di un utente o di un gruppo di tipo (Polo) Metodo a disposizione dei FACTORING (Sbnmarc e non) Se i primi tre caratteri del codice sono XXX si tratta di un utente della struttura (utilizza I.Diretta o Forms amministrazione) Else si tratta di un polo SBNMARC <br>
    * @param codice (polo/gruppo/utente)
    * @return trovato = true/ non trovato = false    */
   public boolean verificaAttivitaDesc( java.lang.String codice,java.lang.String descrizione_attivita )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated     */
   public boolean isInGruppo( java.lang.String utente,java.lang.String gruppo )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Metodo Verifica se l'utente Ã¨ un amministratore <p> Necessario per gestione form Statistiche </p>
    * @param codice utente (12)
    * @return boolean true (amministratore) false    */
   public boolean isAmministratore( java.lang.String codice )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Ritorna vettore parametri semantici <br> torna elenco oggetti costruiti in base all'albero delle abilitazioni <br>
    * @param codice polo
    * @return vettore con i dati richiesti    */
   public java.util.List getParametriSemantica( java.lang.String codice )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Ritorna vettore parametri semantici <br> torna elenco oggetti costruiti in base all'albero delle abilitazioni <br>
    * @param codice utente
    * @return vettore con i dati richiesti    */
   public it.finsiel.sbn.polo.orm.amministrazione.Tbf_bibliotecario getUtente( java.lang.String codice_utente )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Ritorna vettore parametri semantici <br> torna elenco oggetti costruiti in base all'albero delle abilitazioni <br>
    * @param codice utente
    * @return vettore con i dati richiesti    */
   public java.util.List getAttivitaFigli( java.lang.String codice_soggetto,java.lang.String codice_attivita )
      throws RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated Ritorna vettore parametri semantici <br> torna elenco oggetti costruiti in base all'albero delle abilitazioni <br>
    * @param codice utente
    * @return vettore con i dati richiesti    */
   public it.finsiel.sbn.polo.orm.amministrazione.Tbf_biblioteca_in_polo getBiblioteca( java.lang.String cod_polo,java.lang.String cod_biblio )
      throws RemoteException;

   public String getCodicePolo()
   		throws RemoteException;

   // almaviva7 08/07/2008 14.56
   public void reloadProfili() throws RemoteException;
   public void reloadProfilo(String userId) throws RemoteException;
   public void rimuoviProfili(String users) throws RemoteException;
   public void rimuoviProfilo(String userId) throws RemoteException;
   public void reloadCodici() throws RemoteException;

}
