/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.documentofisico;

/**
 * Home interface for CollocazioneBMT.
 * @generated
 * @wtp generated
 */
public interface CollocazioneBMTHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CollocazioneBMT";
   public static final String JNDI_NAME="sbnWeb/CollocazioneBMT";

   public it.iccu.sbn.ejb.domain.documentofisico.CollocazioneBMT create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
