/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.documentofisico;

/**
 * Session layer for CollocazioneBMT.
 * @generated
 * @wtp generated
 */
public class CollocazioneBMTSession
   extends it.iccu.sbn.ejb.domain.documentofisico.CollocazioneBMTBean
   implements javax.ejb.SessionBean
{
   /**
	 * 
	 */
	private static final long serialVersionUID = -513982456756670549L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbRemove()
   {
   }

}
