/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.documentofisico;

/**
 * Home interface for ServiziDocumentoFisico.
 * @generated
 * @wtp generated
 */
public interface DocumentoFisicoBMTHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/DocumentoFisicoBMT";
   public static final String JNDI_NAME="sbnWeb/DocumentoFisicoBMT";

   public it.iccu.sbn.ejb.domain.documentofisico.DocumentoFisicoBMT create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
