/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.documentofisico;

import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.exception.DataException;
import it.iccu.sbn.ejb.exception.ResourceNotFoundException;
import it.iccu.sbn.ejb.exception.ValidationException;
import it.iccu.sbn.ejb.vo.documentofisico.CollocazioneVO;
import it.iccu.sbn.ejb.vo.documentofisico.TitoloVO;
import it.iccu.sbn.polo.orm.bibliografica.Tb_titolo;
import it.iccu.sbn.polo.orm.documentofisico.Tbc_inventario;
import it.iccu.sbn.polo.orm.documentofisico.Tbc_sezione_collocazione;

import java.rmi.RemoteException;
import java.sql.Timestamp;
import java.util.List;

/**
 * Remote interface for DocumentoFisicoCommon.
 * @generated
 * @wtp generated
 */
public interface DocumentoFisicoCommon
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List<TitoloVO> getTitolo( java.lang.String bid,java.lang.String ticket )
      throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getTitoloHib( Tb_titolo titolo,java.lang.String ticket )
      throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws ResourceNotFoundException
    * @throws ApplicationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void assegnaSerieProgr( CollocazioneVO recColl, Timestamp ts,Tbc_sezione_collocazione sezione, int serie, int num, String codMatInv)
      throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws RemoteException
    * @throws ApplicationException
    * @throws DataException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public it.iccu.sbn.ejb.vo.gestionestampe.common.StampeOnlineVO stampeOnline( java.lang.String ticket,it.iccu.sbn.ejb.vo.gestionestampe.common.StampaType tipoStampa,java.util.List parametri )
      throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


   /**
    * <!-- begin-xdoclet-definition -->
    * @throws RemoteException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public void scriviDatiEtichetta(List listaEtichette, Tbc_inventario inventario, String tipoOperazione, String descrBibEtichetta)
   throws java.rmi.RemoteException;

}
