/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.documentofisico;

import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.exception.DataException;
import it.iccu.sbn.ejb.exception.ResourceNotFoundException;
import it.iccu.sbn.ejb.exception.ValidationException;
import it.iccu.sbn.ejb.vo.documentofisico.AggDispVO;
import it.iccu.sbn.ejb.vo.documentofisico.CollocazioneVO;
import it.iccu.sbn.ejb.vo.documentofisico.EsameCollocRicercaVO;
import it.iccu.sbn.ejb.vo.documentofisico.InventarioListeVO;
import it.iccu.sbn.ejb.vo.documentofisico.ModelloDefaultVO;
import it.iccu.sbn.ejb.vo.gestionebibliografica.AreaParametriStampaSchedeVo;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaBollettinoVO;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaBuoniCaricoVO;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaEtichetteVO;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaRegistroConservazioneVO;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaRegistroTopograficoVO;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaRegistroVO;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaStatisticheRegistroVO;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaStrumentiPatrimonioDettaglioVO;
import it.iccu.sbn.ejb.vo.gestionestampe.StampaStrumentiPatrimonioVO;
import it.iccu.sbn.polo.orm.documentofisico.Tbc_collocazione;
import it.iccu.sbn.polo.orm.documentofisico.Tbc_inventario;
import it.iccu.sbn.servizi.batch.BatchLogWriter;

import java.rmi.RemoteException;
import java.util.List;
import java.util.Locale;

/**
 * Remote interface for Inventario.
 * @generated
 * @wtp generated
 */
public interface Inventario
extends javax.ejb.EJBObject
{
	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws RemoteException
	 * @throws ApplicationException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariTitolo( java.lang.String codPolo,java.lang.String codBib,java.lang.String bid,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws RemoteException
	 * @throws ApplicationException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariTitolo( java.lang.String codPolo,List<String> listaBilio,java.lang.String bid,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws RemoteException
	 * @throws ApplicationException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariPossessori( java.lang.String codPolo,java.lang.String codBib,java.lang.String pid,java.lang.String ticket, EsameCollocRicercaVO paramRicerca )
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaSerie( java.lang.String codPolo,java.lang.String codiceBiblioteca,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public it.iccu.sbn.ejb.vo.documentofisico.SerieVO getSerieDettaglio( java.lang.String codPolo,java.lang.String codBib,java.lang.String codSerie,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws Exception
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public it.iccu.sbn.ejb.vo.documentofisico.SerieVO getSerieDettaglio4Import( java.lang.String codPolo,java.lang.String codBib,java.lang.String codSerie,java.lang.String ticket )
	throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean insertSerie( it.iccu.sbn.ejb.vo.documentofisico.SerieVO serie,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws Exception
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean insertSerie4Import( it.iccu.sbn.ejb.vo.documentofisico.SerieVO serie,java.lang.String ticket )
	throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean updateSerie( it.iccu.sbn.ejb.vo.documentofisico.SerieVO serie,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List insertInventario( it.iccu.sbn.ejb.vo.documentofisico.InventarioVO inventario,java.lang.String tipoOperazione,int nInv,java.util.Locale locale,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws Exception
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List insertInventario4Import( it.iccu.sbn.ejb.vo.documentofisico.InventarioVO inventario,java.lang.String tipoOperazione,int nInv,java.util.Locale locale,java.lang.String ticket )
	throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public it.iccu.sbn.ejb.vo.documentofisico.InventarioVO getInventario( java.lang.String codPolo,java.lang.String codBib,java.lang.String codSerie,int codInv,java.util.Locale locale,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws Exception
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public it.iccu.sbn.ejb.vo.documentofisico.InventarioVO getInventario4Import( java.lang.String codPolo,java.lang.String codBib,java.lang.String codSerie,int codInv,java.util.Locale locale,java.lang.String ticket )
	throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @throws DataException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public it.iccu.sbn.ejb.vo.documentofisico.InventarioDettaglioVO getInventarioDettaglio( java.lang.String codPolo,java.lang.String codBib,java.lang.String codSerie,int codInv,java.util.Locale locale,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	public it.iccu.sbn.ejb.vo.documentofisico.InventarioDettaglioVO getInventarioDettaglio( java.lang.String codPolo,java.lang.String codBib,java.lang.String codSerie,int codInv,java.util.Locale locale,java.lang.String ticket,
			boolean includiDatiAcquisizione)
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public int updateInvColl( it.iccu.sbn.ejb.vo.documentofisico.InventarioVO recInvColl,it.iccu.sbn.ejb.vo.documentofisico.CollocazioneVO recColl,java.lang.String tipoOperazione,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws Exception
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public int updateInvColl4Import( it.iccu.sbn.ejb.vo.documentofisico.InventarioVO recInvColl,it.iccu.sbn.ejb.vo.documentofisico.CollocazioneVO recColl,java.lang.String tipoOperazione,java.lang.String ticket )
	throws java.lang.Exception, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean updateCollocazioneScolloca( it.iccu.sbn.ejb.vo.documentofisico.InventarioVO recInvColl,it.iccu.sbn.ejb.vo.documentofisico.CollocazioneVO recColl,java.lang.String tipoOperazione,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean deleteInventario( it.iccu.sbn.ejb.vo.documentofisico.InventarioVO recInvColl,it.iccu.sbn.ejb.vo.documentofisico.CollocazioneVO recColl,java.lang.String tipoOperazione,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean aggiornaInventarioFattura( it.iccu.sbn.ejb.vo.documentofisico.InventarioVO recInv,java.lang.String tipoOp,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaProvenienze( java.lang.String codPolo,java.lang.String codBib,java.lang.String ticket, java.lang.String filtroProvenienza)
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public it.iccu.sbn.ejb.vo.documentofisico.ProvenienzaInventarioVO getProvenienza( java.lang.String codPolo,java.lang.String codBib,java.lang.String codProven,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean insertProvenienza( it.iccu.sbn.ejb.vo.documentofisico.ProvenienzaInventarioVO recProven,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean updateProvenienza( it.iccu.sbn.ejb.vo.documentofisico.ProvenienzaInventarioVO recProven,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @throws DataException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariNonCollocati( it.iccu.sbn.ejb.vo.documentofisico.EsameCollocRicercaVO paramRicerca,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @throws DataException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariDiCollocazione( it.iccu.sbn.ejb.vo.documentofisico.EsameCollocRicercaVO paramRicerca,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariOrdine( java.lang.String codPolo,java.lang.String codBib,java.lang.String codBibO,java.lang.String codTipOrd,int annoOrd,int codOrd,java.lang.String codBibF,java.util.Locale locale,java.lang.String ticket,int nRec )
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariOrdini(List listaOrdini,java.util.Locale locale,java.lang.String ticket,int nRec )
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;
	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariOrdiniNonFatturati( java.lang.String codPolo,java.lang.String codBib,java.lang.String codBibO,java.lang.String codTipOrd,int annoOrd,int codOrd,java.lang.String codBibF,java.util.Locale locale,java.lang.String ticket,int nRec )
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariFattura( java.lang.String codPolo,java.lang.String codBib,int annoF,int progF,java.util.Locale locale,java.lang.String ticket)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaInventariRigaFattura( java.lang.String codPolo,java.lang.String codBib,java.lang.String codBibO,java.lang.String codTipOrd,int annoO,int codO,java.lang.String codBibF, int annoF, int prgF, int rigaF,java.util.Locale locale,java.lang.String ticket)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public InventarioListeVO getInventarioRigaFattura(String codPolo, String codBib, String codBibO, String codTipOrd, int annoOrd, int codOrd, String codBibF,  int annoF, int prgF, int rigaF,
			Locale locale, String ticket)
	throws ValidationException, RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.lang.String getChiaviTitoloAutore( java.lang.String tipo,java.lang.String bidVid,java.lang.String ticket)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public StampaRegistroVO getRegistroIngresso( StampaRegistroVO input,java.lang.String ticket, BatchLogWriter logg)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public StampaStatisticheRegistroVO getStatisticheRegistroIngresso( StampaRegistroVO input,java.lang.String ticket)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getEtichette( StampaEtichetteVO input,java.lang.String tipoOperazione,java.lang.String ticket)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, it.iccu.sbn.ejb.exception.DataException, java.rmi.RemoteException;

	public StampaRegistroTopograficoVO getRegistroTopografico(StampaRegistroTopograficoVO input, String ticket, BatchLogWriter batchLog)
	throws DataException, ApplicationException, ValidationException, java.rmi.RemoteException ;

	public StampaRegistroConservazioneVO getRegistroConservazione(StampaRegistroConservazioneVO input, String ticket, BatchLogWriter batchLog)
	throws DataException, ApplicationException, ValidationException, java.rmi.RemoteException ;

	public StampaStrumentiPatrimonioVO getStrumentiPatrimonioXls(StampaStrumentiPatrimonioVO input, String tipoRegistro, String ticket, BatchLogWriter batchLog)
	throws DataException, ApplicationException, ValidationException, java.rmi.RemoteException ;

//	public StampaStrumentiPatrimonioVO getRegistroConservazioneXls(StampaStrumentiPatrimonioVO input, String ticket, BatchLogWriter batchLog)
//	throws DataException, ApplicationException, ValidationException, java.rmi.RemoteException ;
//
	public StampaBollettinoVO getBollettino(StampaBollettinoVO input, String ticket)
	throws DataException, ApplicationException, ValidationException, java.rmi.RemoteException ;

	public StampaBuoniCaricoVO getBuoniCarico(StampaBuoniCaricoVO input, String ticket)
	throws DataException, ApplicationException, ValidationException, java.rmi.RemoteException ;

	public Integer getContatore(String codPolo,
			String codBib, String codCont, int numInventari, String ticket)
	throws DataException, ApplicationException, ValidationException, java.rmi.RemoteException ;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public ModelloDefaultVO getModelloDefault( java.lang.String codPolo,java.lang.String codiceBiblioteca,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean insertModelloDefault(ModelloDefaultVO modello,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ApplicationException
	 * @throws ResourceNotFoundException
	 * @throws RemoteException
	 * @throws ResourceNotFoundException
	 * @throws RemoteException
	 * @throws DataException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaModelli( java.lang.String codPolo,java.lang.String codBib,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;


	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public it.iccu.sbn.ejb.vo.documentofisico.ModelloEtichetteVO getModello( java.lang.String codPolo,java.lang.String codBib,java.lang.String codModello,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws DataException
	 * @throws ApplicationException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean insertModello( it.iccu.sbn.ejb.vo.documentofisico.ModelloEtichetteVO modello,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;
	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean updateModello( it.iccu.sbn.ejb.vo.documentofisico.ModelloEtichetteVO modello,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;
	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean deleteModello( it.iccu.sbn.ejb.vo.documentofisico.ModelloEtichetteVO modello,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws RemoteException
	 * @throws ApplicationException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public Tbc_collocazione creaCollocazione(Tbc_inventario inventario,CollocazioneVO recColl, String tipoOperazione)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws RemoteException
	 * @throws ApplicationException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public StampaEtichetteVO controllaInput(StampaEtichetteVO input, StampaEtichetteVO output)
	throws ResourceNotFoundException, ApplicationException, ValidationException, DataException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws RemoteException
	 * @throws ApplicationException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public AreaParametriStampaSchedeVo controllaInputSchede(AreaParametriStampaSchedeVo input, AreaParametriStampaSchedeVo output)
	throws ResourceNotFoundException, ApplicationException, ValidationException, DataException, java.rmi.RemoteException;


	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws RemoteException
	 * @throws DataException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean aggiornaInventarioDisponibilita(AggDispVO aggDispVO, String ticket)
	throws DataException, ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public java.util.List getListaSerieDate( java.lang.String codPolo,java.lang.String codiceBiblioteca,java.lang.String ticket )
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public List getListaInventariCollocatiDa(String codPolo, String codBib, String codUtente, String dataDa, String dataA, String ticket)
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	/**
	 * <!-- begin-xdoclet-definition -->
	 * @throws ResourceNotFoundException
	 * @throws ApplicationException
	 * @throws RemoteException
	 * @throws ValidationException
	 * @generated //TODO: Must provide implementation for bean create stub    */
	public boolean getSerieNumeroCarico(java.lang.String codPolo,java.lang.String codiceBiblioteca,String codSerie, String numCarico, String ticket)
	throws it.iccu.sbn.ejb.exception.ResourceNotFoundException, it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

	public StampaStrumentiPatrimonioDettaglioVO elementoStrumentiPatrimonioDettaglio(String ticket,
			Tbc_inventario inventario, String tipoRegistro) throws ApplicationException, RemoteException;

	public boolean inventarioDigitalizzato(String codPolo, String codBibInv, String codSerieInv, int numInv)
			throws ApplicationException, RemoteException;

}
