/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.documentofisico;

/**
 * Home interface for Possessori.
 * @generated
 * @wtp generated
 */
public interface PossessoriHome extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Possessori";
   public static final String JNDI_NAME="sbnWeb/Possessori";

   public it.iccu.sbn.ejb.domain.documentofisico.Possessori create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
