/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.documentofisico;

import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.exception.DataException;
import it.iccu.sbn.ejb.exception.ValidationException;
import it.iccu.sbn.ejb.vo.documentofisico.PossessoriDiInventarioVO;
import it.iccu.sbn.ejb.vo.gestionebibliografica.titolo.AreaDatiPassaggioInterrogazioneTitoloAnaliticaReturnVO;
import it.iccu.sbn.ejb.vo.gestionebibliografica.titolo.AreaDatiPassaggioInterrogazioneTitoloAnaliticaVO;
import it.iccu.sbn.web.keygenerator.GeneraChiave;

import java.rmi.RemoteException;

/**
 * Remote interface for Possessori.
 * @generated
 * @wtp generated
 */
public interface Possessori extends javax.ejb.EJBObject {
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws RemoteException
    * @throws ApplicationException
    * @throws DataException
    * @throws ValidationException
    * @generated //TODO: Must provide implementation for bean create stub    */
   public java.util.List getListaPossessori( java.lang.String codPolo,java.lang.String codBib, it.iccu.sbn.ejb.vo.documentofisico.PossessoriRicercaVO possRic ,int nrec,GeneraChiave key)
      throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public java.util.List getListaPossessori_1( java.lang.String codPolo,java.lang.String codBib, it.iccu.sbn.ejb.vo.documentofisico.PossessoriRicercaVO possRic ,int nrec,GeneraChiave key)
   throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public String inserisciPossessori( it.iccu.sbn.ejb.vo.documentofisico.PossessoriDettaglioVO possDett ,java.lang.String codPolo,java.lang.String codBib,java.lang.String ticket ,GeneraChiave key )
   		throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public String modificaPossessori( it.iccu.sbn.ejb.vo.documentofisico.PossessoriDettaglioVO possDett ,java.lang.String codPolo,java.lang.String codBib,java.lang.String ticket ,GeneraChiave key )
   		throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public String fondiPossessori( it.iccu.sbn.ejb.vo.documentofisico.PossessoriDettaglioVO possDett ,java.lang.String codPolo,java.lang.String codBib,java.lang.String ticket, GeneraChiave key)
		throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;



   public AreaDatiPassaggioInterrogazioneTitoloAnaliticaReturnVO creaRichiestaAnaliticoPossessoriPid(AreaDatiPassaggioInterrogazioneTitoloAnaliticaVO areaDatiPass, String polo ,String bib ,String ticket)	throws RemoteException;
   public AreaDatiPassaggioInterrogazioneTitoloAnaliticaReturnVO cancellaLegamePossessore(String pid_padre,String pid_figlio, String polo ,String bib ,String ticket)	throws RemoteException;
   public AreaDatiPassaggioInterrogazioneTitoloAnaliticaReturnVO cancellaLegameInventario(String pid,String codiceInventario, String polo ,String bib , String uteFirma)	throws RemoteException;

   public String inserisciLegameAlPossessori( it.iccu.sbn.ejb.vo.documentofisico.PossessoriDettaglioVO possDett ,java.lang.String codPolo,java.lang.String codBib,java.lang.String ticket ,GeneraChiave key ,String notaLegame,String tipoLegame)
		throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public String modificaLegameAlPossessori( it.iccu.sbn.ejb.vo.documentofisico.PossessoriDettaglioVO possDett ,java.lang.String codPolo,java.lang.String codBib,java.lang.String ticket ,GeneraChiave key ,String notaLegame,String tipoLegame,String pidOrigine)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public String modificaNotaLegame(String pid_padre,String pid_figlio,String notaLegame,String uteFirma)	throws RemoteException;
   public AreaDatiPassaggioInterrogazioneTitoloAnaliticaReturnVO scambioLegame(String pid_padre,String pid_figlio,String uteFirma)	throws RemoteException;

   public java.util.List getListaPossessoriDiInventario(String codSerie, String codInv , String codBib,String codPolo , String ticket ,int nRec)
   throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public String legamePossessoreInventario (PossessoriDiInventarioVO possInv)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;

   public String modificaLegamePossessoreInventario (PossessoriDiInventarioVO possInv)
	throws it.iccu.sbn.ejb.exception.ApplicationException, it.iccu.sbn.ejb.exception.DataException, it.iccu.sbn.ejb.exception.ValidationException, java.rmi.RemoteException;



}
