/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.amministrazione;

/**
 * Home interface for AmministrazioneGestioneDefault.
 * @generated
 * @wtp generated
 */
public interface AmministrazioneGestioneDefaultHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AmministrazioneGestioneDefault";
   public static final String JNDI_NAME="sbnWeb/AmministrazioneGestioneDefault";

   public it.iccu.sbn.ejb.domain.amministrazione.AmministrazioneGestioneDefault create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
