/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.amministrazione;

import it.iccu.sbn.ejb.exception.ApplicationException;
import it.iccu.sbn.ejb.exception.ValidationException;
import it.iccu.sbn.ejb.vo.amministrazionesistema.PoloVO;
import it.iccu.sbn.ejb.vo.amministrazionesistema.profilazionepolo.GruppoParametriVO;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.CodaJMSVO;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.ElaborazioniDifferiteOutputVo;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.ParametriRichiestaElaborazioneDifferitaVO;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.config.ElaborazioniDifferiteConfig;
import it.iccu.sbn.ejb.vo.elaborazioniDifferite.config.TipoAttivita;
import it.iccu.sbn.ejb.vo.validation.Validator;
import it.iccu.sbn.persistence.dao.exception.DaoManagerException;
import it.iccu.sbn.polo.orm.amministrazione.Tbf_batch_servizi;
import it.iccu.sbn.util.validation.JsScriptSession;
import it.iccu.sbn.vo.custom.amministrazione.BatchAttivazioneVO;
import it.iccu.sbn.vo.custom.amministrazione.OrderedTreeElement;

import java.rmi.RemoteException;
import java.util.List;
import java.util.Map;

import javax.jms.Message;
import javax.jms.Queue;

/**
 * Remote interface for AmministrazionePolo.
 * @generated
 * @wtp generated
 */
public interface AmministrazionePolo
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @throws RemoteException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void loadParameterPolo(  )
      throws it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @throws RemoteException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void createPolo( it.iccu.sbn.vo.custom.Polo polo )
      throws it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @throws RemoteException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public it.iccu.sbn.SbnMarcFactory.util.ParametriHttp getPolo(  )
      throws it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @throws RemoteException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public it.iccu.sbn.SbnMarcFactory.util.ParametriHttp getIndice(  )
      throws it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @throws RemoteException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public it.iccu.sbn.vo.custom.Credentials getCredentials(  )
      throws it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public it.iccu.sbn.ejb.model.unimarcmodel.SbnUserType getUserSbnMarc(  )
      throws it.iccu.sbn.persistence.dao.exception.DaoManagerException, java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void loadCodiciAttivita()
			throws it.iccu.sbn.persistence.dao.exception.DaoManagerException,
			java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public List<Message> getRichieste(String ticket, Queue queue, String baseSelector, Map<String, Object> param)
   			throws DaoManagerException,
   			RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @throws DaoManagerException
    * @generated //TODO: Must provide implementation for bean method stub    */
   public List<BatchAttivazioneVO> getBatchServiziAll()
   			throws it.iccu.sbn.persistence.dao.exception.DaoManagerException,
   			java.rmi.RemoteException;

   public OrderedTreeElement getElencoAttivita(java.lang.String ticket)
   throws it.iccu.sbn.persistence.dao.exception.DaoManagerException,
		java.rmi.RemoteException;

   public String[] getElencoAttivitaProfilo()
   throws it.iccu.sbn.persistence.dao.exception.DaoManagerException,
		java.rmi.RemoteException;

   public List getElencoParametri()
   throws it.iccu.sbn.persistence.dao.exception.DaoManagerException,
	java.rmi.RemoteException;

	public boolean setProfiloPolo(String codicePolo, String codiceUtente,
			  List<String> elencoAttivita,
			  List<GruppoParametriVO> elencoAuthorities,
			  List<GruppoParametriVO> elencoMateriali,
			  List<GruppoParametriVO> elencoSemantica)
			  throws it.iccu.sbn.persistence.dao.exception.DaoManagerException,
				java.rmi.RemoteException;

	public List<String> controllaAttivita(List<String> elencoAttivita) throws DaoManagerException, RemoteException;

	public void clearDBCache() throws RemoteException, DaoManagerException;

	public void checkProfiloIndicePolo() throws DaoManagerException, RemoteException;

	public List<CodaJMSVO> getListaCodeBatch() throws DaoManagerException, RemoteException;

	public List<String> getListaCodeBatchOutput() throws DaoManagerException, RemoteException;

	public CodaJMSVO getCodaBatch(int idCoda) throws DaoManagerException, RemoteException;

	public String prenotaElaborazioneDifferita(
			ParametriRichiestaElaborazioneDifferitaVO richiesta,
			Map<String, Object> properties)
			throws ValidationException, ApplicationException, RemoteException;

	public String prenotaElaborazioneDifferita(
			ParametriRichiestaElaborazioneDifferitaVO richiesta,
			Map<String, Object> properties,
			Validator<? extends ParametriRichiestaElaborazioneDifferitaVO> validator)
			throws ValidationException, ApplicationException, RemoteException;

	public int eliminaRichiesteElaborazioniDifferite(String[] idBatch, Boolean deleteOutputs) throws ValidationException, ApplicationException, RemoteException;

	public String getDescrizioneAttivita(String codAttivita) throws RemoteException;

	public void reloadCodiciSbnMarc() throws RemoteException;

	public void rimuoviProfiliSbnMarc() throws RemoteException;

	public PoloVO getInfoPolo() throws RemoteException, DaoManagerException;

	public void forceBatchStart(String idBatch) throws ValidationException, ApplicationException, RemoteException;
	public void forceBatchStop(String idBatch) throws ValidationException, ApplicationException, RemoteException;

	public Tbf_batch_servizi selectBatchByCodAttivita(String cod_attivita) throws ValidationException, ApplicationException, RemoteException;

	public ElaborazioniDifferiteOutputVo cercaRichiestaElaborazioneDifferita(
			String ticket, String idBatch) throws ValidationException,
			ApplicationException, RemoteException;

	public List<Map<String, Object>> executeSQLCommand(String ticket, String command) throws ValidationException, ApplicationException, RemoteException;

	public ElaborazioniDifferiteConfig getConfigurazioneElaborazioniDifferite(TipoAttivita tipo) throws RemoteException;

	public Map<String, Object> execScript(JsScriptSession executor, String scriptKey, Map<String, Object> params) throws ApplicationException, RemoteException;
}

