/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.amministrazione;

/**
 * Session layer for AmministrazioneBiblioteca.
 * @generated
 * @wtp generated
 */
public class AmministrazioneBibliotecaSession
   extends it.iccu.sbn.ejb.domain.amministrazione.AmministrazioneBibliotecaBean
   implements javax.ejb.SessionBean
{
   /**
	 * 
	 */
	private static final long serialVersionUID = 255305039181050985L;

public void ejbActivate()
   {

   }

   public void ejbPassivate()
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext()
   {
   }

   public void ejbRemove()
   {
   }

}
