/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.amministrazione;

/**
 * Home interface for AmministrazioneGestioneCodici.
 * @generated
 * @wtp generated
 */
public interface AmministrazioneGestioneCodiciHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AmministrazioneGestioneCodici";
   public static final String JNDI_NAME="sbnWeb/AmministrazioneGestioneCodici";

   public it.iccu.sbn.ejb.domain.amministrazione.AmministrazioneGestioneCodici create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
