/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.amministrazione;

/**
 * Home interface for AmministrazioneBiblioteca.
 * @generated
 * @wtp generated
 */
public interface AmministrazioneBibliotecaHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AmministrazioneBiblioteca";
   public static final String JNDI_NAME="sbnWeb/AmministrazioneBiblioteca";

   public it.iccu.sbn.ejb.domain.amministrazione.AmministrazioneBiblioteca create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
