/*
 * Generated by XDoclet - Do not edit!
 */
package it.iccu.sbn.ejb.domain.amministrazione;

import java.rmi.RemoteException;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;

/**
 * Home interface for AmministrazioneGestioneCodici.
 *
 * @generated
 * @wtp generated
 */
public interface AmministrazioneGestioneCodiciBMTHome extends EJBHome {
	public static final String COMP_NAME = "java:comp/env/ejb/AmministrazioneGestioneCodiciBMT";
	public static final String JNDI_NAME = "sbnWeb/AmministrazioneGestioneCodiciBMT";



	public AmministrazioneGestioneCodici create() throws CreateException, RemoteException;

}
