/*******************************************************************************
 * Copyright (C) 2019 ICCU - Istituto Centrale per il Catalogo Unico
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package it.iccu.sbn.ejb.vo.common;

import gnu.trove.THashMap;

import it.iccu.sbn.ejb.utils.ValidazioneDati;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public enum CodiciType {

	CODICE_MATERIALE_BIBLIOGRAFICO2("49", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SI_NO("50", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_REPERTORIO_MARCHE("51", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MATERIALE_BIBLIOGRAFICO_TUTTI("52", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_TIPO_RICERCA_PER_TESTO					("ORTT", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

    // Costanti per specificare il tipo di ricerca di cercaCodice()
	CODICE_AGENZIA_CATALOGAZIONE					("AGEN", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ALTITUDINE_SENSORE						("ALTI", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ATENEI									("RATE", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_CARATTERE_IMMAGINE						("IMMA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_CATEGORIA_FRUIZIONE						("LCFR", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_CATEGORIA_SATELLITE						("CASA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_CATEGORIA_SOGGETTO						("SCSO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_COLORE116								("COLO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_COLORE120								("COLC", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_DESIGNAZIONE_FUNZIONE					("DESF", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_EDIZIONE_CLASSE							("ECLA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ELABORAZIONE								("ELMU", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_FORMA_DOCUMENTO_CARTOGRAFICO				("FODC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_MUSICALE							("FOMU", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_FORMA_PUBBLICAZIONE						("FOPU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_RIPRODUZIONE						("FORI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_GENERE_MATERIALE_UNIMARC					("GEUN", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_GENERE_PUBBLICAZIONE						("GEPU", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_GENERE_RAPPRESENTAZIONE					("GENR", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_INDICATORE_INCIPIT						("ININ", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_INDICATORE_TIPOSCALA						("TISC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LEGAME_DESCRITTORE_DESCRITTORE			("LEDD", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LEGAME_NATURA_TITOLO_TITOLO				("LICR", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LEGAME_TITOLO_AUTORE						("LETA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_LEGAME_TITOLO_MUSICA						("LEMU", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_LEGAME_TITOLO_TITOLO						("LETT", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_LINGUA									("LING", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_LIVELLO_AUTORITA							("LIVE", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MATERIA									("MAMU", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_MATERIALE_BIBLIOGRAFICO					("MATE", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_MATERIALE_GRAFICO						("MAGR", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_MERIDIANO_ORIGINE						("MEOR", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_MOTIVI_DI_CARICO_INVENTARIALE			("CMDC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MOTIVI_DI_SCARICO_INVENTARIALE			("CMDS", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_NATURA_BIBLIOGRAFICA						("NABI", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_NON_DISPONIBILITA						("CCND", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_PAESE									("PAES", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_PIATTAFORMA								("PIAT", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_PRESENTAZIONE							("PRES", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_PROFESSIONI								("RPRF", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_PROVENIENZA								("RPRU", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_PROVENIENZE_OFFERTE						("ATPV", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_PROVINCE									("RPRV", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_PUBBLICAZIONE_GOVERNATIVA				("PUGO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_RESPONSABILITA							("RESP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SISTEMA_CLASSE							("SCLA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_SOGGETTARIO								("SOGG", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STATI_DI_CONSERVAZIONE					("CSCO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STATO_MESSAGGI							("ASME", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STATO_ORDINE								("ASTO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STATO_PARTECIPANTI_GARA					("ATPA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STATO_SUGGERIMENTO						("ASTS", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STESURA									("STES", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STRUMENTI_VOCI_ORGANICO					("ORGA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SUPPORTO_FISICO_PER_CARTOGRAFICO			("SUFC", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_SUPPORTO_FISICO_PER_GRAFICA				("SUFG", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TECNICA_CARTOGRAFIA						("TECN", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TECNICA_DISEGNI							("TECD", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TECNICA_STAMPE							("TECS", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_THESAURO									("STHE", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_LEGAME_TERMINI_THESAURO				("STLT", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_AUTHORITY							("TPAU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_AUTORE								("AUTO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_COLLOCAZIONE						("CTCO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_DATA_PUBBLICAZIONE					("DATA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_DOCUMENTO_DI_RICONOSCIMENTO			("RTDR", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_FATTURA								("ATFA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_INVIO								("ATIN", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_IMPEGNO_ACQUISTO_MATERIALE			("BTMA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_MATERIALE_INVENTARIALE				("CTMI", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_NUMERO_STANDARD						("NSTD", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_ORDINE								("ATOR", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_PARTNER								("RTPA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_PERSONA_GIURIDICA					("RTPG", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_SEZIONE								("CSEZ", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_TESTO_LETTERARIO					("TESL", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_URGENZA								("ATUR", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPOSCALA								("SCAL", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TITOLO_STUDIO							("RTST", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TONALITA									("TONO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_VALUTA									("AVAL", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_IVA										("AIVA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),

	CODICE_TIPO_ADESIONE							("ADES", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_ALLINEAMENTO						("ALLI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_DIMENSIONE								("DIME", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_AUTORE								("FOAU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_DESCRITTORE						("FODE", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_INCIPIT							("FOIN", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_LUOGO								("FOLU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LEGAME_AUTORE_AUTORE						("LEAA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LEGAME_TITOLO_FUSIONE_DUPLICAZIONE		("LELK", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LEGAME_LUOGO_LUOGO						("LELL", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SOTTOTIPO_LEGAME_MUSICA					("LICM", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LEGAME_TITOLO_LUOGO						("LUOG", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_NOTA								("NOTA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_STRUMENTI_VOCI_ORGANICO_PLURALI			("ORGP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	//CODICE_POLO										("POLO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE),
	CODICE_PROIEZIONE								("PROE", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_OPERA								("FOOP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_REPERTORIO								("REPE", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_RILIEVO									("RILI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_CONTROLLO_SIMILITUDINE_AUTHORITY	("SIMA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_CONTROLLO_SIMILITUDINE_DOCUMENTI	("SIMD", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_STRUMENTO_INTERPRETE						("STMU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_RETICOLO_DOCUMENTO					("TIRE", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIMBRO_VOCALE							("TIVO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_ATTIVITA_ITER							("LATT", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STATO_MOVIMENTO							("LSTM", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),

	CODICE_MODALITA_EROGAZIONE						("LMER", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_SERVIZIO							("LTSE", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPI_RIPRODUZIONE_CODICE_SUPPORTO		("LSUP", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_RECORD_RICHIESTA_SERVIZIO			("TRRS", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_STATO_RICHIESTA							("LSTS", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_FUNZIONE_CONTROLLO_ITER					("LFCO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_DOCUMENTO_LETTORE					("CTDL", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_FONTE_DOCUMENTO_LETTORE					("LFON", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_CAMPO_RICHIESTA_WEB						("LMRW", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_CONFIGURAZIONE_URL_OPAC					("LWCO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_CAT_FRUIZIONE_TIPO_SERVIZIO				("TSFC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SISTEMA_METROPOLITANO					("LSME", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_FOLDER_EROGAZIONE_SERVIZI			("LVES", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_SVOLGIMENTO_DEL_SERVIZIO			("LTSS", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_INVIO_SOLLECITO						("LTIS", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	//almaviva5_20150617
	CODICE_TIPO_RINNOVO_AUTOMATICO					("LTRA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	//almaviva5_20151112 servizi ill
	CODICE_TIPO_SERVIZIO_ILL						("LTSI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_STATO_RICHIESTA_ILL						("LSRI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	//CODICE_TIPO_SERVIZIO_ILL_SERVIZIO_LOCALE		("SISL", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_CONDIZIONE_ILL						("LCOI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MODALITA_EROGAZIONE_ILL					("LMEI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SUPPORTO_COPIA_ILL						("LSCI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_RUOLO_BIBLIOTECA_ILL						("LIRB", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_ORDINAMENTO_LISTA_UTENTI					("OLUT", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ORDINAMENTO_LISTA_MATERIE				("OLMA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_SERVIZI				("OLSE", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_AUTORIZZAZIONI			("OLAU", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_TITOLI_STUDIO			("OLTS", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_OCCUPAZIONI			("OLOC", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_MOVIMENTI				("OLMO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_PRENOTAZIONI			("OLPR", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_PROROGHE			    ("OLPO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_GIACENZE			    ("OLGI", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_SOLLECITI				("OLSO", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_SEGNATURE              ("OLSG", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_ORDINAMENTO_LISTA_DOCUMENTO_LETTORE		("OLNS", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),

	CODICE_CATEGORIA_STRUMENTO_MEDIAZIONE			("LCSM", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_CAT_STRUMENTO_MEDIAZIONE_TIPO_MAT_INV	("SMMI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_STATO_PRENOTAZIONE_POSTO					("LSPP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_ORDINAMENTO_TITOLI						("OLTI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ORDINAMENTO_AUTORI						("OIAU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ORDINAMENTO_MARCHE						("OIMA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ORDINAMENTO_LUOGHI						("OILU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_LISTA_MIN_MAX						("TLMM", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_ORDINAMENTO_LISTA_SOGGETTI				("OSSO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_POSIZIONE_DESCRITTORE					("OSPO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ORDINAMENTO_LISTA_CLASSI					("OSCL", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_ORDINAMENTO_LISTA_BATCH					("OFED", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_TIPO_ACQUISIZIONE_MATERIALE				("CTAC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_NOTE_CODIFICATE_INVENTARIO				("CNOT", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TECHE_DIGITALI							("CTEC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_DISP_ACCESSO_REMOTO						("CDDR", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_DIGITALIZZAZIONE					("CDIG", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPI_RIPRODUZIONE_AMMESSI_PER_DOCUM		("CRIP", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_PROGRESSIVO_INVENTARIO				("CTNI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SUPPORTO_COPIA							("CSUP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_NATURA_INVENTARIO						("CINA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_ORDINAMENTO_LISTA_COLLOCAZIONI			("OCCO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ORDINAMENTO_LISTA_POSSESSORI				("OCPP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_TIPO_RELAZIONE                           ("LTRE", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	//I seguenti 3 codici sono relativi a righe della tabella Trl_relazioni_servizi
	CODICE_TIPO_SERVIZIO_MOD_EROGAZIONE             ("TSME", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_SERVIZIO_CATEGORIA_FRUIZIONE        ("TSCF", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_SUPPORTO_MODALITA_EROGAZIONE        ("SUME", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_RUOLO_BIBLIOTECARI						("RRUO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_TIPI_BIBLIOTECA							("RTBI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPI_MESSAGGIO							("ATME", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_NATURA_ORDINE							("AONA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ORDINAMENTO_LISTA_ORDINI					("OAOR", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_STATI_CONTINUATIVO						("AOCO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_PERIODICITA								("PPER", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_STATO_FASCICOLI							("PSFA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_FASCICOLI							("PTFA", CodiciOrdinamentoType.ORDINAMENTO_PER_DESCRIZIONE_ASC),
	CODICE_TIPO_NUMERAZIONE_FASCICOLO				("PFNU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	//almaviva5_20111122 evolutive CFI
	CODICE_EDIZIONE_SOGGETTARIO						("SEFI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	//almaviva5_20121120 evolutive google
	CODICE_REGIONE									("RREG", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_TIPO_ESTRAZIONE_UNIMARC					("ETEU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ETICHETTE_UNIMARC						("ETUN", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_ESTRAZIONE_ETICHETTE_UNIMARC		("TEEU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	CODICE_BATCH_PIANIFICABILE						("PIED", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	//almaviva5_20131014 evolutive google2
	CODICE_MODELLO_URI_COPIA_DIGITALE				("CMUD", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	//almaviva5_20140929 evolutiva area0
	CODICE_TIPO_VIDEO								("TIVI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_INDICATORE_COLORE						("INDC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_INDICATORE_SUONO							("INDS", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SUPPORTO_DEL_SUONO						("SUSU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LARGHEZZA_O_DIMENSIONI					("LARG", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_PUBBLICAZIONE_DISTRIBUZIONE		("FODI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TECNICA_VIDEOREGISTRAZIONI_E_FILM		("TEVI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_PRESENTAZIONE_IMMAGINI_IN_MOVIMENTO("FPIM", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MATERIALE_ACCOMPAGNAMENTO				("MACC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_PUBBLICAZIONE_VIDEOREGISTRAZIONI	("PUVI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_PRESENTAZIONE_VIDEOREGISTRAZIONI	("PRVI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_PUBBLICAZIONE_AUDIOVIDEO			("FPUB", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_VELOCITA									("VELO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_SUONO								("TISU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LARGHEZZA_DELLA_SCANALATURA				("LASC", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TECNICA_REGISTRAZIONE					("TERE", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MATERIALE_EMULSIONE_BASE					("EMUL", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MATERIALE_SUPPORTO_SECONDARIO			("MASU", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_STANDARD_TRASMISSIONE					("STRA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_VERSIONE									("VERS", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_ELEMENTI_DELLA_PRODUZIONE				("ELEP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SPECIFICHE_CATEGORIE_COLORE				("SCCF", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_EMULSIONE_DELLA_PELLICOLA				("EMUP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_COMPOSIZIONE_DELLA_PELLICOLA				("COPE", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_SUONO_PER_IMMAGINI_IN_MOVIMENTO		("TISI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_PELLICOLA_O_STAMPA					("TIPE", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_STATO_DETERIORAMENTO						("SDET", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_COMPLETEZZA								("COMP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_DIMENSIONE_DEL_NASTRO					("DINA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_LARGHEZZA_DEL_NASTRO						("LANA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_CONFIGURAZIONE_DEL_NASTRO				("CONA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MATERIALE_TESTUALE_ACCOMPAGNAMENTO		("MATA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SPECIALI_CARATTERISTICHE_RIPRODUZIONE	("SCAR", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_DISCO								("TDIS", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_MATERIALE							("TIMA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_TAGLIO								("TITA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_FORMA_DEL_CONTENUTO						("FOCO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_CONTENUTO							("TICO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_MOVIMENTO								("MOVI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_DIMENSIONALITA							("BIDI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SENSORIALITA								("SENS", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_RISORSA_ELETTRONICA					("RIEL", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_INDICAZIONE_SPECIFICA_MATERIALE			("DESI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_COLORE									("CDCO", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_DIMENSIONI								("CDDI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_SUONO									("SUON", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_CONTENUTO_LETTERARIO_MODERNO				("COLM", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_CONTENUTO_LETTERARIO_ANTICO				("COLA", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_INDICATORE_TESTO_LETTERARIO				("INDT", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),
	CODICE_TIPO_MEDIAZIONE							("MEDI", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	//almaviva5_20150505 evolutiva area5
	CODICE_SUPPORTO_AUDIOVIDEO						("SUAV", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	//almaviva5_20150929 sbnmarc v2.01
	CODICE_TIPO_SUPPORTO							("SUPP", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC),

	//almaviva5_20160322 sbnmarc v2.02
    CODICE_LINK_ALTRA_BASE_DATI                     ("LINK", CodiciOrdinamentoType.ORDINAMENTO_PER_CODICE_ASC);


	////////////////////////////////////////////////////////////////////////////////

	////////////////////////////////////////////////////////////////

	public static final String JNDI_CODICE = "sbn.Codici.codici";
	public static final String JNDI_TIPO_CODICE = "sbn.Codici.tipoCodice";

	public enum CodiciRicercaType {
		RICERCA_CODICE_SBN,
		RICERCA_CODICE_UNIMARC,
		CODICE_LEGAME_TITOLO_TITOLO,

		RICERCA_CODICE_SBN_ULTERIORE,
		RICERCA_CODICE_UNIMARC_ULTERIORE;
	}

	private static Map<String, CodiciType> values;
	private final String tp_tabella;
	private final CodiciOrdinamentoType tp_ordinamento;

	static {
		CodiciType[] codici = CodiciType.class.getEnumConstants();
		values = new THashMap<String, CodiciType>();
		for (int i = 0; i < codici.length; i++)
			values.put(codici[i].tp_tabella, codici[i]);
	}

	public static final CodiciType fromString(String value) {
		if (ValidazioneDati.strIsNull(value) )
			return null;
		return CodiciType.values.get(value.trim() );
	}

	private CodiciType(String tp_tabella, CodiciOrdinamentoType tp_ordinamento) {
		this.tp_tabella = ValidazioneDati.trimOrEmpty(tp_tabella);
		this.tp_ordinamento = tp_ordinamento;
	}

	public final String getTp_Tabella() {
		return this.tp_tabella;
	}

	public final CodiciOrdinamentoType getTipoOrdinamento() {
		return tp_ordinamento;
	}

	public static void main(String... args) {
		//check duplicati
		Set<String> types = new HashSet<String>(CodiciType.values().length);
		System.out.println("--- INIZIO TEST ---");
		for (CodiciType c : CodiciType.values()) {
			String tp_tabella = c.getTp_Tabella();
			if (types.contains(tp_tabella))
				System.out.println("Codice duplicato: " + tp_tabella);
			else
				types.add(tp_tabella);
		}
		System.out.println("--- FINE TEST ---");
	}

}
